### PR TITLE
Added 'ver' action with current version to all necessary rules (fix for #650)

### LINKED ISSUE #650: Consistent support for the "ver" action
Many rules have support for the `ver` action, but far from all. Namely the 949 rules are lacking.

We should add consistent support.

### PR DESCRIPTION
**Pull request by airween**
This PR fixes #650.

A small footnote for this modification: I generated a [spreadsheet](https://docs.google.com/spreadsheets/d/1x6tg8RyAELw0h4y1uoMEi3rPiLfrNFpK598kyXLtogs/edit#gid=1586050007) for the better visibility of changes.

The column E/F contains the status of actions before, J/K after the modification. The `PL control` is a formula, if the `id` of the rule is ended up with `...011`, `...012`. If it's "yes", then `Need 'ver' act.` is "no". This means the `PL control` rules didn't got the `ver` action now.

`Need to add` column is "yes" if the action should be at rule (it's not PL control rule) but there isn't yet. If this is "yes" the script added it.

If the rule needs the `ver` and contains it after the modification, then the `Check` field is `OK` - but doesn't matter that the action was present or not. All fields must be `OK` in this column.

The `Changed` fields indicates that a change has been made (was not present before - it present after).

Definition of `PL control`: 
```
id < 1000000 and (id % 1000 >= 100 or id % 1000 <= 10)
  or
id > 1000000
```
I think this form describes the rules with `skipAfter` actions and doesn't affect exclusion rules. The modification affects all other `SecRule` and `SecAction` entries.

Let me know if there are still missing any `ver` action, or if it's unnecessary.

Note, of course, the modification follows the [expected sequence of actions](https://github.com/SpiderLabs/owasp-modsecurity-crs/wiki/Order-of-ModSecurity-Actions-in-CRS-rules).

### CODE REVIEW

**Comment by fzipi** [comment]
Now that I see this one, shouldn't we use `3.3` as version?

**Comment by airween** [comment]
> Now that I see this one, shouldn't we use `3.3` as version?

we've discussed about the version, and the conclusion was we can use the 3.2, as in cas of every other rule.

**Comment by fzipi** [comment]
Cool. So we merge this one, and if we need in the future we update everything to the needed version.

**Comment by franbuehler** [comment]
In the monthly chat meeting from May 4 we decided to merge this PR:
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1749#issuecomment-623634756

**Pull request merged**
