### PR TITLE
Fix path traversal attack pattern at id:930110

### PR DESCRIPTION
**Pull request by airween**
There is an issue at ModSecurity repo: https://github.com/SpiderLabs/ModSecurity/issues/2149.

Thanks @fgsch.

### CODE REVIEW

**Comment by fgsch** [comment]
LGTM 👍

**Comment by lifeforms** [comment]
Awesome, thanks @airween !

**Comment by jammasterj89** [comment]
To be PCRE compatible, shouldn't the regex be:

```
(?:^|[\\\/])\.\.(?:[\\\/]|$)

**Comment by dune73** [comment]
No, PCRE is fine without format. Or why do you think that's not the case? (Is the unit test failing?)

**Comment by jammasterj89** [comment]
@dune73 No, whilst debugging an issue I noticed regex101.com said the regex wasn't PCRE compatible. Just thought it was worth raising, no problem if not.

**Comment by dune73** [comment]
I see. ModSec uses PCRE with a wee bit different configuration. That's why. Thank you for reporting anyway.

**Comment by airween** [comment]
@jammasterj89 

> @dune73 No, whilst debugging an issue I noticed regex101.com said the regex wasn't PCRE compatible. Just thought it was worth raising, no problem if not.

please note, that the Apache converts the double `\\` to single, so the existing pattern at rule:
`(?:^|[\\/])\.\.(?:[\\/]|$)`
will evaluated as
`(?:^|[\/])\.\.(?:[\/]|$)`
which is correct IMHO.

Your pattern:
`(?:^|[\\\/])\.\.(?:[\\\/]|$)` will transform to `(?:^|[\\/])\.\.(?:[\\/]|$)` - what you want to avoid, perhaps :).

But please check that with the regression tests (through the Apache).

**Pull request merged**
