### PR TITLE
Fixing trailing whitespace in various rules

### PR DESCRIPTION
**Pull request by csanders-git**

### CODE REVIEW

**Comment by lifeforms** [comment]
sad trombone :(

**Comment by lifeforms** [comment]
Also `util/integration/.cache` and `util/integration/__pycache__` should probably be removed from the repo and added to `.gitignore`.

**Comment by csanders-git** [comment]
Yes to that -- i'll add those but it is having problems finding the travis.yml not sure why :(

**Comment by csanders-git** [comment]
@lifeforms Hazzah travis has woken up and we are cooking with fire :) fixing the .gitignore

**Comment by csanders-git** [comment]
alright @lifeforms travis says we're good to push. Do you concur with our new overlords feelings?

**Comment by lifeforms** [comment]
Yesh!!!

**Pull request merged**
