### PR TITLE
Refactoring ModSecurity CRS Branch v3.0/dev

### PR DESCRIPTION
**Pull request by soufianebenali**
These changes implement part 1 of the agreed refactoring explained in #1600:

- Create a new folder tests in the root folder
- Move util/regression-tests/ -> tests/regression/, and util/integration/ -> tests/integration
- Rename folder documentation/ to docs/
- Create folder examples/ and move crs-setup.conf.example -> examples/crs-setup.conf

### CODE REVIEW

**Comment by fgsch** [comment]
This is EOL. Not sure if we should push any further changes to this branch.

**Comment by emphazer** [comment]
in my opinion, we shouldn't...

**Comment by bittner** [comment]
Thank you both for your feedback. We didn't know this. That's fine for us.

Should we close this PR unmerged?

**Comment by fgsch** [comment]
Yeah, please do. Thanks.

**Pull request closed without merging**
