### PR TITLE
 Fixing whitespace according to standard for 3.1/dev

### PR DESCRIPTION
**Pull request by fzipi**
Well... have to redo #859 for 3.1/dev.

Seems good to me, but maybe another eyes can tell me if I'm wrong.

### CODE REVIEW

**Comment by dune73** [comment]
Looks good to me. Ready to merge.

```
crs-pull-873>ls rules/*.conf | while read F; do diff -w ../crs-official-v3-1-dev/$F $F; done
266c266
<             chain
---
>         "chain"
268c268
<                 ctl:requestBodyAccess=Off
---
>             "ctl:requestBodyAccess=Off"
279c279
<             chain
---
>         "chain"
281c281
<                 chain
---
>             "chain"
283c283
<                     chain
---
>                 "chain"
285c285
<                         ctl:requestBodyAccess=Off
---
>                     "ctl:requestBodyAccess=Off"
297c297
<             chain
---
>         "chain"
299c299
<                 chain
---
>             "chain"
301c301
<                     chain
---
>                 "chain"
303c303
<                         ctl:requestBodyAccess=Off
---
>                     "ctl:requestBodyAccess=Off"
53,54d52
< 
< 
148,149c148,151
<   SecRule &TX:block_harvester_ip "@eq 0" "chain"
<   SecRule &TX:block_spammer_ip "@eq 0" "chain"
---
>     SecRule &TX:block_harvester_ip "@eq 0" \
>         "chain"
>         SecRule &TX:block_spammer_ip "@eq 0" \
>             "chain"
307d308
< 
82d81
< 
74c74,75
< 	SecRule &TX:dos_counter_threshold "@eq 0" "chain"
---
>     SecRule &TX:dos_counter_threshold "@eq 0" \
>         "chain"
85c86,87
< 	SecRule &TX:dos_counter_threshold "@eq 0" "chain"
---
>     SecRule &TX:dos_counter_threshold "@eq 0" \
>         "chain"
229d228
< 
1392d1391
< 
1535d1533
< 
362d361
< 
172d171
< 
165d164
< 
594d593
< 
65,66d64
< 
< 
673d670
< 
1332d1331
< 
148d147
< 
97d96
< 
117d116
< 
538d537
< 
114d113
< 
149d148
< 
172d171
< 
72d71
< 
37d36
< 
123d121
< 

```


@csanders-git : Am I right that Travis runs only on `v3.0/dev` PRs, and not on v3.1?

**Comment by emphazer** [comment]
looks good to me too

**Comment by dune73** [comment]
@emphazer: Do you want to merge? I'm a bit busy ...

**Comment by emphazer** [comment]
sure, i can do

**Pull request merged**
