### PR TITLE
Add PUBLIC identifier for XML entities

### PR DESCRIPTION
**Pull request by Rufus125**
Currently only the SYSTEM identifier is found, but as per XML documentation, also the PUBLIC identifier can be used:
https://www.w3.org/TR/xml/#sec-external-ent

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for this welcome PR @Rufus125 and sorry for not getting back to you earlier.

We would like to merge this.

Unfortunately, we had an update on this rule since you submitted and now we are facing a merge conflict on the rule. Do you want to resolve this yourself or should we do this for you?

**Comment by Rufus125** [comment]
I merged the change, hopefully now everything should be good to go :)

**Comment by dune73** [comment]
Thank you.

But now it seems like you duplicated the `SYSTEM` string. Or am I wrong?

**Comment by Rufus125** [comment]
@dune73 Yeah you are correct, thanks for reviewing the merge!

**Comment by dune73** [comment]
No worries mate. That's the reason we do reviews. :)

**Comment by dune73** [comment]
Time to merge. Thank you for the PR @Rufus125.

**Pull request merged**
