### PR TITLE
Resolves issue #663: libinjection XSS FP with 'on' in URLs

### PR DESCRIPTION
**Pull request by franbuehler**
Removed check of request header referer from rule 941100 on PL1 and added new rule 941101 on PL2 which checks request header referer again.
Resolves issue #663.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for the pull, @franbuehler.

You are repeating the check for all the arguments in 941101. That way you run the same check a 2nd time, while I thought the idea was to check the other arguments in PL1 in 941100 and then in PL2 in 941101 check for the Referer header.

Is there a reason to do it that way? Can't you just strip 941101 of all the arguments but Referer?

**Comment by franbuehler** [comment]
Of course, you're right. Made an update.

**Comment by dune73** [comment]
Thanks.

But let me continue my nitpicking: Why did you add the 941101 at the end of the PL2 rules and not sorted by rule ID as the first PL2 rule?

**Comment by dune73** [comment]
Looks good. Thank you.

**Comment by dune73** [comment]
Checked. Works as advertised. Ready to merge.

**Comment by lifeforms** [comment]
It's interesting to note that due to splitting the rule to a new rule id, we did create a possible new false positive for users. :P This is just a note and not to fault anyone; at the time of this PR we didn't have the release policy yet to not introduce new rule ids for bugfix releases.

So for any users who upgraded to 3.0.2, if you had excluded rule 941100 due to false positives in the referer header, then you may want to now exclude rule 941101 now too.

**Comment by dune73** [comment]
You have a point. Let's keep this in mind the next time we do this. It would be simple to indicate it in the CHANGES and / or release notes.

**Pull request merged**
