### PR TITLE
Fixing executing paranoia level counters

### PR DESCRIPTION
**Pull request by dune73**
This brings #1196 to v3.2/dev and also includes the same fixes for 914 and additional rules in 920.

### CODE REVIEW

**Comment by csanders-git** [comment]
after resolving conflicts I think this will be good, but i'll test when they are resolved.

**Comment by dune73** [comment]
Oopsie. I'll get back to this. Overlooked the conflicts.

**Comment by dune73** [comment]
Conflicts fixed. @csanders-git: could you do your review now?

**Comment by lifeforms** [comment]
The PR needs a bit of case changes: `matched_var_name` -> `MATCHED_VAR_NAME`.
That will ensure compatibility with ModSec 3.0.0-2.

We applied those changes to 3.1 separately, but this PR doesn't have them yet.

@fgsch will apply them to this PR and then we can merge it.

**Comment by fgsch** [comment]
Updated.

**Comment by dune73** [comment]
Thank you very much, @fgsch. Glad you guys noted this. Could somebody merge this please?

**Comment by dune73** [comment]
Thanks @lifeforms.

**Pull request merged**
