### PR TITLE
Add catastrophic backtracking detection to TravisCI

### PR DESCRIPTION
**Pull request by franbuehler**
This PR adds @s0md3v's oneliner to TravisCI (see https://twitter.com/s0md3v/status/1119645565845823489).
Builds will fail if a catastrophic backtracking is detected in a rule in rules/*.

This PR should only be merged if we no longer have such problems.
Otherwise, future builds will fail ;)

### CODE REVIEW

**Comment by franbuehler** [comment]
TravisCI fails because of existing catastrophic backtracking...

**Comment by fgsch** [comment]
This should be in script and not before_install IMO.
Also, this incorrectly matches on e.g. `..\*)+`.

**Comment by franbuehler** [comment]
I added it early in the pipeline because I want to fail fast.
Isn't that correct?

**Comment by franbuehler** [comment]
What about that:
`(?:([*+])|{\d+,\d*})\)(?:\1|{\d+,\d*})`

**Comment by fgsch** [comment]
It is not incorrect but technically the tests run in script, and that's where we do all the testing atm (including whitespace, and ensuring that the format is valid).

**Comment by fgsch** [comment]
Also you probably want to exclude commented out lines.

**Comment by franbuehler** [comment]
I moved the check to scripts...

**Review by s0md3v — CHANGES_REQUESTED** [review]
```
((?<!\\)[*+]|{\d+,\d*})\)((?<!\\)*[*+]|{\d+,\d*})
```

Use negative lookbehind to match `*)+` but not `\*)+`

**Comment by franbuehler** [comment]
I get an error message: "The preceding token is not quantifiable" with this part of the regexp `((?<!\\)*`
Should I delete this `*` after the second negative lookbehind?

**Comment by s0md3v** [comment]
@franbuehler Yes, that was a typo, sorry.

**Comment by franbuehler** [comment]
Thank you, @s0md3v.

**Comment by franbuehler** [comment]
@dune73 [21:51 Uhr]
Thought: Can 1371 be hard fail and come with a list of rules where we accept 1371 to fail and then we shorten the list?
Step by step?

**Comment by franbuehler** [comment]
@airween developed a more sophisticated solution that will soon be added to TravisCI.

**Pull request closed without merging**
