### PR TITLE
Update filenames within files to reflex new 9xx filename structure

### PR DESCRIPTION
**Pull request by csanders-git**
This is an update as listed in #416 . It is essentially the remainder of the update that changed filenames to REQUEST-9xx from REQUEST-xx

### CODE REVIEW

**Comment by dune73** [comment]
For the renamed files RESPONSE-50-*, you need to do REQUEST-xx to REQUEST-9xy. (e.g., 50 -> 952). Otherwise it all looks neat and tidy.

**Comment by csanders-git** [comment]
Sorry i'm a little confused by that comment, what?

**Comment by dune73** [comment]
Sorry for being so brief.

Another example: Following my pull, the file is now  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf 

But an example skip marker in your PR is END-RESPONSE-950-DATA-LEAKAGES-IIS when it should be END-RESPONSE-954-DATA-LEAKAGES-IIS.

**Comment by csanders-git** [comment]
Ahh interesting - looks like it was actually a problem from before. Yeah good eye - i'll fix those right up :)

**Comment by csanders-git** [comment]
Should be fixed :)

**Comment by dune73** [comment]
Yes, it was my fault. Thanks for fixing.

**Pull request merged**
