### PR TITLE
remove unused rule 901180 (tx.protected_uploads)

### PR DESCRIPTION
**Pull request by lifeforms**
Delete some vestigial remains of removed functionality.

### CODE REVIEW

**Comment by fgsch** [comment]
LGTM.

**Comment by dune73** [comment]
Here too. Ready to be merged.

**Comment by dune73** [comment]
@lifeforms, will you apply to 3.2 too?

**Comment by lifeforms** [comment]
@dune73 Yes I'll do that shortly!

**Comment by lifeforms** [comment]
It's not needed to cherry-pick this to v3.2, since in v3.2/dev the variable does get used (rule 9142050)

**Pull request merged**
