### PR TITLE
Make CRS variables configurable

### PR DESCRIPTION
**Pull request by franbuehler**
I applied my changes from my CRS container and made CRS variables configurable (https://hub.docker.com/r/franbuehler/modsecurity-crs-rp).
Tested and built with the files:

- Dockerfile-2.9-apache
- Dockerfile-3.0-apache
- Dockerfile-3.0-nginx

I'll extend the description (README) as soon as you think this PR is fine.

### CODE REVIEW

**Comment by franbuehler** [comment]
Test:

```
docker build -t my-crs . -f Dockerfile-2.9-apache
```

```
docker run -dti -p 80:8001    -e PARANOIA=1    -e EXECUTING_PARANOIA=2    -e ENFORCE_BODYPROC_URLENCODED=1    -e ANOMALYIN=10    -e ANOMALYOUT=5    -e ALLOWED_METHODS="GET POST PUT"    -e ALLOWED_REQUEST_CONTENT_TYPE="text/xml|application/xml|text/plain"    -e ALLOWED_REQUEST_CONTENT_TYPE_CHARSET="utf-8|iso-8859-1"    -e ALLOWED_HTTP_VERSIONS="HTTP/1.1 HTTP/2 HTTP/2.0"    -e RESTRICTED_EXTENSIONS=".cmd/ .com/ .config/ .dll/"    -e RESTRICTED_HEADERS="/proxy/ /if/"    -e STATIC_EXTENSIONS="/.jpg/ /.jpeg/ /.png/ /.gif/"    -e MAX_NUM_ARGS=128    -e ARG_NAME_LENGTH=50    -e ARG_LENGTH=200    -e TOTAL_ARG_LENGTH=6400    -e MAX_FILE_SIZE=100000    -e COMBINED_FILE_SIZES=1000000 my-crs
```

**Comment by csanders-git** [comment]
Amazing!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (there is not enough time to write out the number of exclamation marks)

**Comment by csanders-git** [comment]
We should also generate a README doc with this for dockerhub.

**Comment by franbuehler** [comment]
Thank you :-)

I will open a PR for the Dockerhub README.

Is it this one? 
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/util/docker/README.md

You could then proofread and correct it, ok?

**Comment by csanders-git** [comment]
yup that is the one -- i will proofread after :)

**Pull request merged**
