### PR TITLE
920310: Expanding whitelist to additional UA

### PR DESCRIPTION
**Pull request by dune73**
This adds an UA to the 920310 whitelist in order to avoid unwanted false positives.
The description of the rule is also expanded a bit.

See issue #366 for details.

### CODE REVIEW

**Comment by dune73** [comment]
See issue #370 for the special case where this rule is not firing (false negative).

**Comment by dune73** [comment]
See related PR #389 as well. Hope they do not conflict.

**Comment by csanders-git** [comment]
There are some conflicts and your branch seems to have more than just this change in it now. Can you fix this conflict - otherwise I think i'll have to submit a new PR with the same data.

**Comment by dune73** [comment]
Oops. Did not notice that.

The change also expands the comment with some explanations. Something PR #389 did as well. I thought I had coordinated the two PRs, but apparently git does not share this view.

Will investigate.

**Comment by csanders-git** [comment]
Rather small change but it looks good. Good work!

**Comment by dune73** [comment]
Small. But effective against FPs. Thanks for merging.

**Pull request merged**
