### PR TITLE
Add NGINX Docker and Travis Testing support.

### PR DESCRIPTION
**Pull request by csanders-git**

### CODE REVIEW

**Comment by csanders-git** [comment]
Testing for FTW is waiting on https://github.com/SpiderLabs/ModSecurity/tree/d810de9166794be2bee972fffb0e09cb0b8d6ec5

Any idea when this will be merged into master @victorhora or should i make our docker image read from a diff branch?

**Comment by dune73** [comment]
What are we doing with this PR? It's outdated / conflicting and should probably started anew. Also in light of @franbuehler's addition to the official docker container slowly approaching the pipeline.

**Comment by dune73** [comment]
@csanders-git has picked this up again. It's being discussed in crscontainers on OWASP slack. He has a draft new base container. There for 1 week for reviews now, then @franbuehler and @danehrlich1 will pick it up from there.
@csanders-git will rebase this PR afterwards.

**Comment by ghost** [comment]
Was this ever rebased?

**Comment by csanders-git** [comment]
@danehrlich1 no going to be completely replaced with the new docker image

**Comment by csanders-git** [comment]
Closing as an updated version has been pushed upstream

**Pull request closed without merging**
