### PR TITLE
PR to resolve issue #243: semicolon in FILES

### PR DESCRIPTION
**Pull request by franbuehler**
Extended regex in rule id 920120 with negative look behind assertions to allow html entities in files.
Added new rule 920121 on PL2 with original, short and stricter regex.

Resolves issue #243.

### CODE REVIEW

**Comment by csanders-git** [comment]
@franbuehler thank you for your submission. I plan to take some time today to test it out.

**Comment by dune73** [comment]
Tested this. Works as advertised. Ready to merge from my side.

**Comment by csanders-git** [comment]
Ran through a number of test case scenario's seems to work well. I'd say yes to merging as all

**Comment by dune73** [comment]
Here we go. Thank you @franbuehler.

**Pull request merged**
