### PR TITLE
Fix regression tests.

### PR DESCRIPTION
**Pull request by studersi**
This pull request fixes/reimplements some of the disabled regression tests and activates them in `owasp-modsecurity-crs/util/regression-tests/tests/`.

### CODE REVIEW

**Comment by studersi** [comment]
This is ready to be merged now.

**Comment by fgsch** [comment]
Sorry for the delay but could you break down into multiple PRs please?

**Comment by studersi** [comment]
Yes, I can do that. Will do it over the weekend. How should I split them up? One PR per rule that is tested or one PR per test?

**Comment by fgsch** [comment]
Thank you! One PR per test file would be great.

**Comment by studersi** [comment]
I created the separate pullrequests for each file. Closing this one.

**Comment by fgsch** [comment]
Thank you! We'll take a look.

**Pull request closed without merging**
