### PR TITLE
Add file to the list of schemes

### PR DESCRIPTION
**Pull request by fgsch**
Also ensure we match regardless of the case everywhere.

### CODE REVIEW

**Comment by fgsch** [comment]
Rebased to v3.0/dev as per comment in #726.

**Comment by dune73** [comment]
Thank you. Glad you spotted the missing case instruction.

**Comment by fgsch** [comment]
No problem.  Just pushed an update as I've missed one rule.

Let me know if anything else needs my attention.

**Review by csanders-git — APPROVED** [review]
This looks good however we should also add a rule for protecting against ip's in integer notation (adding a separate ticket)

**Comment by dune73** [comment]
Not sure I get you, @csanders-git. Could you give an example, please?

**Pull request merged**
