### PR TITLE
Fix counters

### LINKED ISSUE #1178: Fix anomaly scoring in 933190, 932180, 920341; complete response rules are doing this wrong too
## Type of Issue
Clearly a bug fix

## Description
@fgsch noticed on slack that the rule ids above are not setting the anomaly scores for the PLs correctly. Not sure how this happened. Maybe merge failures.

It seems that this whole executing PL stuff does not cover the responses at all. Should be checked seperately.

## Your Environment
irrelevant

## Confirmation

Check rules of IDs name in title

### PR DESCRIPTION
**Pull request by fgsch**
anomaly_score and outbound_anomaly_score should refer to their paranoia
level counterpart (i.e. _plN).

Fixes #1178.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for fixing my broken patch, @fgsch. I checked it and it looks good. PL execution on tested rules you fixed works fine.

 You are now basing this against v3.1. Can we do v3.2 first? 

P.S. If aiming for 3.2, the REQUEST-914 rules have the same issue. At least there is an excuse with those.

**Comment by fgsch** [comment]
I can do but I think we should concentrate in 3.1 first to get another rc out before the final release.

**Comment by dune73** [comment]
@csanders-git: How do you want this done? 3.1 because we should be fast now and then fixed in 3.2 as well. Or the usual way around?

**Comment by jianting060** [comment]
Nginx -t error when detecting rules: REQUEST-914-FILE-DETECTION.conf. Line: 70. Column: 85.
SecRule ARGS|XML|XML:/* \
    "@rx ^(?:\x4d\x5a(?:\x90|\x50)|\x7f\x45\x4c\x46)" \
    "id:914100,\
    phase:2,\
    **block,\**
    msg:'Possible harmful executable file detected',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAMES}: %{MATCHED_VARS}',\

**Comment by fgsch** [comment]
@jianting060 not sure I follow. That file does not exist in v3.1/dev, which is the focus of this PR.

**Comment by dune73** [comment]
No news from @csanders-git. So I am going to merge against 3.1. 

Thank you for the PR @fgsch.

I will do the PR for 3.2 myself. This mess is my fault after all.

**Pull request merged**
