### PR TITLE
Resolves issue 661.

### PR DESCRIPTION
**Pull request by damienmckenna**
Adds an item to rule 9001160.
Removes 9001120.
Removes 9001150.

### CODE REVIEW

**Comment by franbuehler** [comment]
Hi  damienmckenna, 

I felt free to review your pull request.
It looks good!
But I think you deleted too much. I would leave the comments (lines 78, 80, 222-227) where they are. I consider them as general comments, not rule dependant.
And I think you should do your pull request against 3.0/dev instead of 3.0/master?

Regards,
Franziska

**Comment by csanders-git** [comment]
Does the ARGS:form_build_id not affect  9001120?

**Comment by damienmckenna** [comment]
I removed lines 80 and 222-227 because they were related to the rule in 228-233, without the rule the comments seemed redundant?

**Comment by franbuehler** [comment]
Ok, I see.
I saw these lines as a kind of skeleton, a rule id reservation. So it's easier to decide where to add new rules.
But maybe you're right and it makes no sense to leave these comments.
Other thoughts?

**Comment by dune73** [comment]
Just to get this correct, you attempt to simplify the Rule Exclusions by consolidating two rules into 9001160.
Do I get this correct.

I think the deleted comments are really not needed anymore. But there is definitely a comment missing in 9001160 (-> 942440 not listed in the comments).

**Comment by franbuehler** [comment]
That's also like I understand it.

Before pull request:

- 9001160 – removes 942450 for ARGS:form_build_id in general 
- 9001120 – removes 942440 for ARGS:form_build_id for an admin path
- 9001150 – removes 942440 for ARGS:form_build_id for another admin path

Pull request now adds the removing of 942440 for ARGS:form_build_id to rule 9001160.
And therefore rule 9001120 and 9001150 are obsolete. The rule 942440 is now already removed for ARGS:form_build_id in 9001160.

**Comment by dune73** [comment]
So we have a common interpretation here. Thank you @franbuehler.

So I am ready to merge and will then add a little PR of my own to add the missing comment to 9001160. Any objections?

**Comment by csanders-git** [comment]
@dune73 I ran some limited tests on this, It seemed to work, is your modification just a comment?

**Comment by dune73** [comment]
Yes, just a comment. I guess I could also do this directly, can't I?

@franbuehler also noted that PR goes against master and not against dev. Is there a way to change this or do I duplicate the PR?

**Comment by dune73** [comment]
So I recreated this PR as #698. Essentially the same, but pointing to v3.0/dev instead of master. Than a bit of tweaking with the comments and done.

Thank you @damienmckenna for picking this up - and sorry for taking ages to review a simple patch improving rule layout.

**Pull request closed without merging**
