### PR TITLE
Update regression tests for 931130.

### PR DESCRIPTION
**Pull request by studersi**
See pull request https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1350 for more information.

### CODE REVIEW

**Review by franbuehler — APPROVED** [review]
Tests pass now. PR can be merged.

5 passed in 1.84 seconds

**Comment by fgsch** [comment]
Looks good.

Could you possible add a negative test (a test that does not match) that uses a scheme in the query string but shares the host?

**Comment by fgsch** [comment]
Alternatively, if you are happy @dune73 we can merge this as is and add the positive test in a separate PR.

**Comment by dune73** [comment]
The negative test, you mean @fgs? As long as said test is coming, I do not mind either way.

@studersi : When do you have time for this?

**Comment by studersi** [comment]
That's fine with me. You can merge this pull request, open a new issue, and assign it to me. I can probably write the positive test this weekend.

**Comment by dune73** [comment]
Thank you for the PR and thank you for volunteering. I have now merged thi PR and opened #1404. We can not assign to non-project people unfortunately. Glad we could merge this; too many open PRs.

**Pull request merged**
