### PR TITLE
Add exception for Monit status check

### LINKED ISSUE #1566: Rule 920350: ignore local access to /server-status
##  Type of Issue
Rule 920350 fires when `/server-status` is accessed from localhost.
I think when the client and the source ip is `127.0.0.1` this should be ignored.

### Apache error log
```
[Fri Sep 27 00:28:07.689517 2019] [:error] [pid 12888] [client 127.0.0.1:58544] [client 127.0.0.1] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/"] [unique_id "XY07d-9OYIaH28nIRmEipgAAAAU"]
[Fri Sep 27 00:28:07.693336 2019] [:error] [pid 12884] [client 127.0.0.1:40326] [client 127.0.0.1] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/server-status"] [unique_id "XY07d9BiZ9M6npLZaX-n9AAAAAE"]
```

### modsec_audit.log
```
--2db62405-A--
[27/Sep/2019:00:28:07 +0200] XY07d-9OYIaH28nIRmEipgAAAAU 127.0.0.1 58544 127.0.0.1 443
--2db62405-B--
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: Monit/5.26.0
Accept: */*
Accept-Encoding: identity
Connection: close

--2db62405-F--
HTTP/1.1 200 OK
Last-Modified: Mon, 02 Sep 2019 12:27:20 GMT
ETag: "2d-5919117e77f01"
Accept-Ranges: bytes
Content-Length: 45
Cache-Control: max-age=604800
Expires: Thu, 03 Oct 2019 22:28:07 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer-when-downgrade
Feature-Policy: accelerometer 'none';ambient-light-sensor 'none';autoplay 'none';camera 'none';encrypted-media 'none';fullscreen 'self';geolocation 'self';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'self';picture-in-picture 'none';speaker 'self';sync-xhr 'none';usb 'none';vibrate 'none';vr 'none'
Content-Security-Policy: default-src 'self' ; img-src 'self' data: ; style-src 'self' data: ; font-src 'self' data: ; script-src 'self' ; object-src 'none' ; base-uri 'none' ;
Connection: close
Content-Type: text/html

--2db62405-E--
<html><body><h1>It works!</h1></body></html>

--2db62405-H--
Message: Warning. Pattern match "^[\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 127.0.0.1] ModSecurity: Warning. Pattern match "^[\\\\\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/"] [unique_id "XY07d-9OYIaH28nIRmEipgAAAAU"]
Stopwatch: 1569536887687114 4562 (- - -)
Stopwatch2: 1569536887687114 4562; combined=1885, p1=618, p2=852, p3=69, p4=177, p5=169, sr=107, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.2.0.
Server: Apache
Engine-Mode: "ENABLED"

--2db62405-Z--
```

```
--3dc7d050-A--
[27/Sep/2019:00:28:07 +0200] XY07d9BiZ9M6npLZaX-n9AAAAAE 127.0.0.1 40326 127.0.0.1 80
--3dc7d050-B--
GET /server-status?auto HTTP/1.1
Host: 127.0.0.1
Accept: */*
User-Agent: Monit/5.26.0
Connection: close

--3dc7d050-F--
HTTP/1.1 200 OK
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer-when-downgrade
Feature-Policy: accelerometer 'none';ambient-light-sensor 'none';autoplay 'none';camera 'none';encrypted-media 'none';fullscreen 'self';geolocation 'self';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'self';picture-in-picture 'none';speaker 'self';sync-xhr 'none';usb 'none';vibrate 'none';vr 'none'
Content-Length: 1252
Connection: close
Content-Type: text/plain; charset=ISO-8859-1

--3dc7d050-E--
127.0.0.1
ServerVersion: Apache/2.4.41 (Debian) OpenSSL/1.1.1d
ServerMPM: prefork
Server Built: 2019-08-14T04:42:29
CurrentTime: Friday, 27-Sep-2019 00:28:07 CEST
RestartTime: Friday, 27-Sep-2019 00:12:03 CEST
ParentServerConfigGeneration: 1
ParentServerMPMGeneration: 0
ServerUptimeSeconds: 963
ServerUptime: 16 minutes 3 seconds
Load1: 0.06
Load5: 0.07
Load15: 0.11
Total Accesses: 409
Total kBytes: 2687
Total Duration: 122209
CPUUser: 26.83
CPUSystem: 10.11
CPUChildrenUser: 5.14
CPUChildrenSystem: 1.13
CPULoad: 4.48702
Uptime: 963
ReqPerSec: .424714
BytesPerSec: 2857.2
BytesPerReq: 6727.35
DurationPerReq: 298.799
BusyWorkers: 3
IdleWorkers: 7
Scoreboard: _W___C_K_.._..........................................................................................................................................
TLSSessionCacheStatus
CacheType: SHMCB
CacheSharedMemory: 512000
CacheCurrentEntries: 21
CacheSubcaches: 32
CacheIndexesPerSubcaches: 88
CacheTimeLeftOldestAvg: 147
CacheTimeLeftOldestMin: 19
CacheTimeLeftOldestMax: 297
CacheIndexUsage: 0%
CacheUsage: 1%
CacheStoreCount: 119
CacheReplaceCount: 0
CacheExpireCount: 98
CacheDiscardCount: 0
CacheRetrieveHitCount: 44
CacheRetrieveMissCount: 1
CacheRemoveHitCount: 0
CacheRemoveMissCount: 0

--3dc7d050-H--
Message: Warning. Pattern match "^[\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 127.0.0.1] ModSecurity: Warning. Pattern match "^[\\\\\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "127.0.0.1"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/server-status"] [unique_id "XY07d9BiZ9M6npLZaX-n9AAAAAE"]
Apache-Handler: server-status
Stopwatch: 1569536887692294 3226 (- - -)
Stopwatch2: 1569536887692294 3226; combined=1984, p1=537, p2=940, p3=46, p4=342, p5=119, sr=105, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.2.0.
Server: Apache
Engine-Mode: "ENABLED"

--3dc7d050-Z--
```

## Your Environment
* CRS version (e.g. v3.0.2): latest git: commit 8ab05a16cf2d81c232975628ca1fe35af471c35d
* ModSecurity version (e.g. 2.9.2): 2.9.3-1+b1
* Web Server and version (e.g. apache 2.4.27): 2.4.41-1
* Operating System and version: Debian unstable

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

### PR DESCRIPTION
**Pull request by fzipi**
Fixes #1566.

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
I absolutely agree with this PR! What about making something similar for all monitoring agents? I mean handle requests from Nagios, Elasticsearch Metricbeat, etc... 

We could even put two new variables in crs-setup.conf to make users set monitoring agents source IP/class and user agent... what do you think? Something like:

`SecRule REMOTE_ADDR "@ipMatch %{tx.monitoring_ip_list}" ...`
`SecRule REQUEST_HEADERS:User-Agent "@rx %{tx.monitoring_user_agent_rx}" ...`

**Comment by fgsch** [comment]
Should we perhaps have an exclude file for all agents?

**Comment by theMiddleBlue** [comment]
maybe just 2 variables, something that users can configure like `tx.restricted_extensions`

**Comment by fgsch** [comment]
Same question as in #1585 re checking the IP address first.

**Comment by fzipi** [comment]
Yeah, that makes a lot of sense.
Do you think we should merge this one to solve the particular issue, and then create a new one with this discussion?

**Comment by fgsch** [comment]
Personally I'd change it to check the IP first and consider whether we want to have a new exclusion file after it hits the tree but no strong feelings either way.

**Comment by spartantri** [comment]
I would prefer to have this disabled by default and let the sysadmin to enable themselves as this is could eventually turned into a bypass

**Comment by theMiddleBlue** [comment]
just for further evaluations: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-apache.html

**Comment by fzipi** [comment]
Ok, what I will do now is close this one in favour of a broader approach covering more tools using a data file.

**Comment by fzipi** [comment]
New issue to follow this is #1589 .

**Pull request closed without merging**
