### PR TITLE
Fix 942101 (and 942460) by adding to sqli_score variable

### PR DESCRIPTION
**Pull request by dune73**

### CODE REVIEW

**Review by fgsch — APPROVED** [review]
👍

**Comment by fgsch** [comment]
We also might want to include 942101 here.

**Comment by dune73** [comment]
942101? I don't understand... 942101 is included, is not it?

**Comment by fgsch** [comment]
Ignore me. Had a lapse.

**Comment by dune73** [comment]
Can you merge, please? If you think it's OK...

**Comment by fgsch** [comment]
Merged!

**Comment by dune73** [comment]
thanks!

**Pull request merged**
