### PR TITLE
example to url rule 920220

### PR DESCRIPTION
**Pull request by coolt**
add example

### CODE REVIEW

**Comment by dune73** [comment]
This is a PR out of the DINACon Hacknight in Berne. The idea is to add an example payload to existing rules.

https://hacknight.dinacon.ch/project/4

**Comment by dune73** [comment]
Looks good. Ready to merge.

**Comment by franbuehler** [comment]
Thank you for your PR. Please add a slash after localhost.

**Comment by dune73** [comment]
Oops.

**Pull request merged**
