### PR TITLE
Switch to multiple issue templates

### PR DESCRIPTION
**Pull request by fgsch**
Use the new version of issue templates.

### CODE REVIEW

**Comment by dune73** [comment]
Very nice. Thank you.

False negatives: Could you add a remark about the security-file and that it may be more appropriate to reach us that way if the bypass is severe.

Is it possible label the new issues based on the template being used?

Other than that, I think this is merge-worthy. :)

**Comment by fgsch** [comment]
I will update the false negative wording.

As for the labels, the issues will be labelled automatically based on the template.

**Comment by fgsch** [comment]
Wording updated.

**Comment by dune73** [comment]
Awesome. I'll merge as soon as Travis completes its job.

**Comment by dune73** [comment]
Thank you very much.

**Pull request merged**
