### PR TITLE
Add Wappalyzer as outlined in #1190

### PR DESCRIPTION
**Pull request by csanders-git**

### CODE REVIEW

**Review by dune73 — COMMENTED** [review]
That was quick, thanks.

You see this UA as a crawler and not as a scanner. What is your reasoning?

**Comment by csanders-git** [comment]
yeah, didn't think it was really doing security sensitive stuff - just more OSINT

**Comment by dune73** [comment]
Makes sense. Thanks for the PR.

**Comment by dune73** [comment]
Could this be backported to 3.1?

**Comment by csanders-git** [comment]
I think it's too late for that :-)

**Comment by dune73** [comment]
ACK

**Pull request merged**
