### PR TITLE
Remove old and unwanted constructs

### PR DESCRIPTION
**Pull request by fgsch**
Related to #1121.

### CODE REVIEW

**Comment by dune73** [comment]
Wow, this is impressive.

tx.msg in referenced in the 980xxx rules. Would you mind erasing it there as well?

I'm all for merging this.

**Comment by csanders-git** [comment]
w00t I agree this will simplify rules greatly

**Comment by fgsch** [comment]
@dune73 will do and update this PR.

**Comment by dune73** [comment]
Appreciated. Thanks.

Also appreciate that this very useful PR carries the number 1327. 1327 is the year in which Umberto Eco's "Name of the Rose" happens.  #FunFacts

**Comment by fgsch** [comment]
Updated.

**Comment by emphazer** [comment]
@fgsch i wasn't able to find any issues after some tests.
good PR, thx.

**Comment by ghost** [comment]
Umberto Eco has a personal library of 30,000 books. There is a video of it on YouTube somewhere of his apartment in Spain with all the books. Beautiful.

I would like to have a library like that one day :)

**Comment by fgsch** [comment]
Updated to cover latest changes in master and also the 2 scripts referencing these constructors.

**Comment by lifeforms** [comment]
We like this PR, but the `tx.%{rule.id}` construct is used in one particular place, the RESPONSE-981-DEBUG.conf file. It spits out these variables for debugging. So this would break that old debug hack. But the debug hack is not widely known, and maybe nobody (except me) uses it. So then, we could clean up the technical debt.

Decision: I'll ask on the mailinglist if anyone is depending on that debug mode, if so then we do this merge. We will get back to it.

Then the file RESPONSE-981-DEBUG.conf can also be deleted from the repo.

**Comment by dune73** [comment]
So what do we do @lifeforms?

**Comment by lifeforms** [comment]
Nobody cared about it (edit: the tx.{%ruleid} construct), let's delete it 👍

**Comment by na1ex** [comment]
> 
> 
> Nobody cared about it, let's delete it 👍

Maybe too late : I have some tooling to replay auditlog that makes use of it for fast (>200 test/sec) non-regression testing.

**Comment by fgsch** [comment]
@na1ex is it using tx.%{rule.id}.., tx.msg, or both?

**Comment by na1ex** [comment]
> 
> 
> @na1ex is it using tx.%{rule.id}.., tx.msg, or both?

Tool uses tx.%{rule.id} only ( each matching rule-id is added in a single response header for check. )

**Comment by lifeforms** [comment]
> Tool uses tx.%{rule.id} only ( each matching rule-id is added in a single response header for check. )

RESPONSE-981-DEBUG.conf uses this mechanism too. Sadly it will break when we remove this variable. As you say, it can make for very fast testing. However, not many people were using this feature (in fact you are the first I know!). That said, it's a tradeoff, but we had to choose, and we decided to remove these variables and make our rule writing easier for newbies.

**Comment by na1ex** [comment]
Trade-off understood, just wanted to mention the use.
Note : these are magical rules gone to a treasure drawer to be re-discovered (someday :o).

**Comment by dune73** [comment]
Anything else before we merge this PR?

**Comment by lifeforms** [comment]
LGTM!

**Comment by dune73** [comment]
Well, then let's get rolling!

Thank for this swift PR @fgs. This is huge.

**Comment by lifeforms** [comment]
Great work @fgsch !

**Pull request merged**
