### PR TITLE
added regression test for 942490

### PR DESCRIPTION
**Pull request by emphazer**
image

the regression test for PR #985

### CODE REVIEW

**Comment by emphazer** [comment]
@csanders-git 
the checks have failed because you use v3.1/dev of your branch in the travis docker image.
the screenshot is made with your docker image but changed your forked repo to the original of spiderlabs.

**Comment by csanders-git** [comment]
not quite sure why this is still failing -- took care of quite a few issues with the builds. Before i go farther and add support for v3, i'd like to get this working.

**Comment by csanders-git** [comment]
I could have squashed these -- wasn't expecting the rebase to include them all.. but it seems to be passing the test you added

https://travis-ci.org/SpiderLabs/owasp-modsecurity-crs/builds/351787816#L846

**Comment by emphazer** [comment]
Great! So we can merge it?

**Comment by dune73** [comment]
@csanders-git: What's the exact status here?

**Comment by csanders-git** [comment]
So perhaps the easiest way to fix this would be to just make another PR with only the changes.

**Comment by emphazer** [comment]
finally!!!

**Comment by emphazer** [comment]
@csanders-git 
this PR had in the end 2 goals!

you updated the regression tests with travis etc.
and i learned how to run gitlab via runner with your docker crs, to do auto regression tests like travis :-)

**Comment by csanders-git** [comment]
Would you like help on making the new PR. The easiest way will be to add a remote upstream. Fetch that upstream. Checkout matter. Then create a new branch locally. Copy over any changed files and push to your branch

**Comment by emphazer** [comment]
@csanders-git 
done :-)

**Pull request closed without merging**
