### PR TITLE
First pass at removing unneeded capture groups

### PR DESCRIPTION
**Pull request by fgsch**
While here also remove some unnecessary capture actions.

### CODE REVIEW

**Comment by fgsch** [comment]
Part of #839

**Comment by dune73** [comment]
Thank you for the PR, @fgsch. I think we have not talked about the unneeded capture groups before. However, I see it loosely related to the rule cleanup project outlined in #808. Is that correct and should we tag this PR and the new issue that you made with that rule cleanup tag.

Also: Could you describe the steps and techniques you use in this PR in a few words. Not everybody is a regex king...

**Comment by fgsch** [comment]
It's indeed loosely related but I decided to handle this separately since the process is somewhat manual. I'm happy for you to add the rule cleanup tag as long as we treat them as separate things (e.g. they don't block each other).

Regarding the steps and techniques, I will address it in a separate comment.

**Comment by dune73** [comment]
OK. Back to this one. It was all nice and beautiful, but we let it lay around too long and now it has settled some dust.

I'm ready to merge, but we have merged the whitespace PR to v3.0/dev in the meantime. And I also think this should go against v3.1/dev (and later considered for backporting).

When rebasing against v3.1/dev it might be worth considering the parallel whitespace PR coming out of rule cleaning as well. This is meant to be pushed in quickly too.

If that's settled, I'm ready to merge.

**Comment by fgsch** [comment]
OK, I will rebase this against 3.1 and update this PR.

**Comment by dune73** [comment]
Thank you.

**Comment by fgsch** [comment]
Updated. 

I've split the changes across 2 commits, one for the removal of capture groups, and one for the capture action.

As I mentioned this is the first of more commits to address it.

**Comment by fgsch** [comment]
Updated after the merge of #897.
As a bonus removed the trailing spaces to make the CI happy.

**Comment by fgsch** [comment]
Updated after the merge of #897.
As a bonus removed the trailing spaces to make the CI happy.

**Comment by dune73** [comment]
Hope to find time to look into this (and many other PRs) today.

**Comment by dune73** [comment]
I took a closer look and it looks quite good.

However, I think some of the capture actions you remove are necessary. For example in 920420, where the match is referenced as TX:0 in the chained rule.

**Comment by fgsch** [comment]
You are correct. I got confused with MATCHED_VAR, sorry. 
I will correct this and repush.

**Comment by dune73** [comment]
Please do. And please check the other ones as well. I am not sure it all caught my attention.

**Comment by fgsch** [comment]
I've removed the commit altogether for now so this only deals with the capture groups (and the trailing space for travis' sake).

**Comment by dune73** [comment]
OK. I looked again. No hard regressions seen anymore.

However, I am really afraid of killing functionality in areas where we do not have unit tests. This is a fairly dangerous PR.

Could somebody else take a close look too?

Also, is this meaning to do away with _every_ unnecessary capture group or only some of them?

**Comment by fgsch** [comment]
> Also, is this meaning to do away with every unnecessary capture group or only some of them?

All of them.

**Comment by dune73** [comment]
I'm not really sure I look at the right things, but how about 942440?

**Comment by dune73** [comment]
Other than that, I have ran extensive tests on this PR and it looks OK AFAICT.

I am inclined merge after some more clarifications. Anybody disagree?

**Comment by lifeforms** [comment]
Visually walked through this PR and done some very quick tests, I see no problems!

**Comment by dune73** [comment]
OK, I'll wait for a response on 942440 from @fgsch and then I'll merge.

**Comment by fgsch** [comment]
Re 942440, I have misunderstood your question. 
Since this requires manual verification I've decided to split the work in multiple PRs.

This work is meant to eventually do all of them but this PR only covers some.
Sorry for the misunderstanding.

**Comment by dune73** [comment]
So we can merge this, but then there will be additional PRs? (-> OK with me)

**Comment by fgsch** [comment]
@dune73 yup, that's the idea.

**Comment by dune73** [comment]
Thank you, @fgsch. Merging.

**Pull request merged**
