### PR TITLE
Fix typos in initialization default settings

### LINKED ISSUE #506: Buggy default value checks in REQUEST-901-INITIALIZATION.conf
Quite a few of the default value checks in the 901 init file are buggy as they overwrite values set in crs-setup.conf.

Example:

```
SecRule &TX:tx.inbound_anomaly_score_threshold "@eq 0" \
    "id:901100,\
    phase:1,\
    pass,\
    nolog,\
    setvar:tx.inbound_anomaly_score_threshold=5"

# Default Outbound Anomaly Threshold Level (rule 900110 in setup.conf)
SecRule &TX:tx.outbound_anomaly_score_threshold "@eq 0" \
    "id:901110,\
    phase:1,\
    pass,\
    nolog,\
    setvar:tx.outbound_anomaly_score_threshold=4"
```

I won't be able to do a PR before the afternoon.

### PR DESCRIPTION
**Pull request by lifeforms**
Fixes #506.

### CODE REVIEW

**Comment by lifeforms** [comment]
Funny, the syntax coloring would have made this typo obvious, should have made that earlier :)

syntax

**Comment by dune73** [comment]
Checked. Works. Thanks for the quick fix.

**Comment by csanders-git** [comment]
yikes good catch ;)

**Comment by dune73** [comment]
It was a lucky catch.

**Pull request merged**
