### PR TITLE
920310: exclude FP causing "Business" client, add comments

### LINKED ISSUE #515: 920310 (Missing Accept Header) firing on Exchange autodiscover (again)
I see quite a few FPs from a variety of IPs for

``` 
"GET /autodiscover/autodiscover.xml HTTP/1.1" ... "Business/6.6.1.2 CFNetwork/758.5.3 Darwin/15.6.0"
```

We have talked about this a big deal in #366. It looks like Business was a synonym for Enterprise. At least they got the orthography right with this one.

### PR DESCRIPTION
**Pull request by lifeforms**
Resolves #515 .

### CODE REVIEW

**Comment by dune73** [comment]
Thanks.

Would you mind explaining the welcome reference to specific CRS issues like the following?
```
... (CRS issue #515)
```

**Comment by lifeforms** [comment]
Done

**Comment by dune73** [comment]
Thank you.

**Comment by csanders-git** [comment]
Can i have an HTTP request to add to the regression tests?

**Comment by lifeforms** [comment]
@csanders-git 

1) Should hit 920310:
```
GET / HTTP/1.1
Host: example.com
Accept:
User-Agent: lol
```

2) Should not hit 920310:
```
GET / HTTP/1.1
Host: example.com
Accept:
User-Agent: Business/6.6.1.2 CFNetwork/758.5.3 Darwin/15.6.0
```

3) Should not hit 920310:
```
GET / HTTP/1.1
Host: example.com
Accept:
User-Agent: Entreprise/6.5.0.177 CFNetwork/758.4.3 Darwin/15.5.0
```

**Comment by csanders-git** [comment]
:) thanks @lifeforms adding now

**Pull request merged**
