### PR TITLE
Panic with error 500 on unconfigured CRS

### LINKED ISSUE #479: What to do with people using the CRS2 setup.conf with CRS3?
The anomaly scoring limit var changed its name to name but one of the several significant changes.

So what if people take the easy path from CRS2 to CRS3 without updating their setup.conf. In the worst case, the CRS would stop blocking things with CRS3.

It's too late for RC1, but we need a solution for the final release. Tagging this RC2.

### PR DESCRIPTION
**Pull request by lifeforms**
If the CRS is not configured correctly (detected by tx.setup_done), panic with error 500.

Resolves #479.

### CODE REVIEW

**Comment by lifeforms** [comment]
I included `ctl:auditEngine=on` to try everything we can to get the error message logged, not knowing the default settings.

I included `ctl:ruleEngine=on` because on my example box, `DetectionOnly` happened to be the default, and so I still didn't get the error 500 after deleting my setup conf, but it could be debated if we want to do override `ctl:ruleEngine`.

**Comment by dune73** [comment]
No. I think the ruleEngine setting is something we should not touch.
Otherwise, just fine.

**Comment by lifeforms** [comment]
@dune73 You're right. Removed it.

**Comment by lifeforms** [comment]
@csanders-git I reeeeeeaaaaaaaaaallly want to always log to the audit log though, even if some other rule might have disabled it... But if you think it's totally inappropriate I'll remove it.

**Comment by lifeforms** [comment]
Removed both `ctl` instances. Not worth spending more of our time on such a minor detail. Ready for merge!

**Comment by dune73** [comment]
Almost ready to merge.

Your message starts with `ModSecurity CRS is unconfigured. ... `. Thinking of a CRS newbie, you might want to be more clear here. Let me propose `ModSecurity Core Rules deployed without base configuration! ...`  Given the status 500, the exclamation mark seems warranted to me.

**Comment by lifeforms** [comment]
Improved the error message.

**Comment by dune73** [comment]
Time to merge. Thanks you @lifeforms.

**Pull request merged**
