### PR TITLE
Narrowing down subregex .*? in 941130

### PR DESCRIPTION
**Pull request by dune73**

### CODE REVIEW

**Comment by fzipi** [comment]
Excellent, my OCD is now pleased :rofl:

**Comment by fzipi** [comment]
LGTM

**Comment by fzipi** [comment]
There is a third case, internal entities. Do we need them?

Because in that case, the regexp won't match. See [here](https://www.w3.org/TR/REC-xml/#sec-entity-decl) and [here](https://www.xml.com/pub/a/98/08/xmlqna2.html) for examples.

My pcretest says:
```
   re> /(?i)[\s\S]!ENTITY\s+(?:\S+|%\s+\S+)\s+SYSTEM\b/
data> <!ENTITY entityname "replacement text">
No match
data> <!ENTITY entityname SYSTEM "replacement text">
 0: <!ENTITY entityname SYSTEM
```

**Comment by dune73** [comment]
My gut feeling tells me, internal entities are less useful and thus less dangerous, namely for paranoia level 1. And also that this must be harder to detect as there is no longer a 2nd keyword like `SYSTEM` involved.

**Comment by fzipi** [comment]
Fair enough. Merging.

**Comment by dune73** [comment]
Thank you!

**Pull request merged**
