### PR TITLE
Drop unneeded capture groups and tidy up regexp (cont'd)

### PR DESCRIPTION
**Pull request by fgsch**
Continued from #1252.

After this:

```
901420 groups 1
901440 groups 1
910140 groups 1
912150 groups 1
920480 groups 1
920440 groups 1
921180 groups 1
931130 groups 1
942130 groups 1
942430 groups 1
942420 groups 1
942431 groups 1
942421 groups 1
942432 groups 1
943110 groups 1
901430 groups 2
920190 groups 2
941220 groups 136
941210 groups 168
```

Next PR will cover the last 2. The rest are valid.

### CODE REVIEW

**Review by franbuehler — COMMENTED** [review]
Cool PR, thank you! The rules are easier to read than before. 

**rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf**
941190: Both Regexes tested, works
941250: tested, works
941330: tested, works -> is much easier to read now, cool!

**rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf**
942230: tested, works
942130: generated, looks good
942180: looks good -> maybe we could slightly change the comment for this rule 942180?
from: 
```
# Note that after assemble an outer bracket with an ignore case flag is added
# to the Regexp::Assemble output:
```

to:
```
# Note that after assemble an ignore case flag is added to the outer bracket:
(?: -> (?i:
```

942440: tested, works

**util/regexp-assemble/regexp-942130.data**
Looks good!

**util/regexp-assemble/regexp-942180.data**
Looks good!

Apache can be started. PR looks good!

**Comment by fgsch** [comment]
> 942180: looks good -> maybe we could slightly change the comment for this rule 942180?

Good point. I will update it.

**Comment by fgsch** [comment]
Updated after @franbuehler's comment.

**Review by franbuehler — APPROVED** [review]
This PR is ready to be merged.

**Comment by dune73** [comment]
Thank you for the PR and the review. Merging now.

**Comment by lifeforms** [comment]
Awesome!!!!

**Pull request merged**
