### PR TITLE
Added CONTRIBUTING guidelines

### PR DESCRIPTION
**Pull request by fzipi**
This is a base file to discuss if these guidelines are good enough for contributors.

I'm doing this PR against this branch, can be cherry-picked to v3.1/dev afterwards.

Please comment and/or rewrite as needed!

### CODE REVIEW

**Comment by dune73** [comment]
Thank you @fzipi. This is a good start, but we'll need to talk about this some time as per your suggestion.

I'd like to merge this to `v3.1/dev` first. Then we can talk about backporting, but personally I do not see much sense in this.

Adding a remark with regards to doing PRs against the `v3.1/dev` file would also be worthwhile.

Your indentation example does not really adhere to the proposed style. At least not on my screen, please check.

We need a description of the tagging system we use. Given we think about overhauling this, a FIXME might do for the time being.

This is what springs to me right now. Not necessarily exhaustive list, though. Thank you for your initiative; really makes sense.

**Comment by spartantri** [comment]
a sample rule template ready to copy paste would be nice :)
there are no naming conventions for vars and markers and rule id numbering

**Comment by fzipi** [comment]
Excellent comments!

**Comment by fzipi** [comment]
I will close this one, and create a new one for v3.1/dev with your comments added.

**Pull request closed without merging**
