### PR TITLE
removing Rule 920150, it's redundent

### PR DESCRIPTION
**Pull request by csanders-git**
This pull request deals with rule 920150 as denoted in #437

### CODE REVIEW

**Comment by dune73** [comment]
Please check my remark in #437 before merging.

**Comment by dune73** [comment]
With the new setup.conf making this very clear, I am open for a merge. If I do not hear objections, I am going to merge.

Btw. we might push a `tx.recommended_rules=1` into the official recommended ModSec rules. It would be years before we could depend on it, but it would really be helpful for issues like the one here.

**Comment by csanders-git** [comment]
@dune73 i have no objections, I think at some point we should work on an install script maybe - might look like make where it finds apache and installs to it or nginx etc -- checking that there is a modsecurity.conf default, but this isn't critical as people package this and most people wouldn't need/use it.

**Comment by dune73** [comment]
Sounds like a plan!

**Pull request merged**
