### PR TITLE
Added two rules against HTTP Parameter Pollution

### PR DESCRIPTION
**Pull request by franbuehler**
I've added the HTTP Parameter Pollution rules to solve issue #400. 

What I've done:
- Added 2 new rules: id: 921170 and id: 921180 (id 921180 is chained)
- Put them in REQUEST-921-PROTOCOL-ATTACK.conf (another possibility was REQUEST-920-PROTOCOL-ENFORCEMENT.conf, but I think this suits best)
- Added a description which I partially took from old experimental_rules/modsecurity_crs_40_http_parameter_pollution.conf

### CODE REVIEW

**Comment by dune73** [comment]
Nice one.

One issue, I see: 921180 has two pass actions.

**Comment by umbruch** [comment]
10 out of 10 for this :+1:

**Comment by eyenx** [comment]
:+1:

**Comment by dune73** [comment]
Hello @franbuehler,

I've run a series of tests against this new rule pair. As expected, there have been a few false positives, but mostly limited to traffic I derived from a single site. With the attack traffic, there were two alerts on attack traffic.

This is a rule which will rarely trigger real positives, but if it does, we are facing an advanced attack. Therefore a ratio with a lot of FPs and few legitimate alerts is not unexpected. That's why you are aiming for PL3, actually.

The rules work as advertised. I tested with the following payloads (-> as reference for @csanders-git):

"a=abc&b=def" -> OK
"a=abc&a=def" -> FAIL
"a1=abc&a11=def" -> OK

The description is good at explaining the problem and the solution.


Still, I have a few minor things which could be improved before we merge this. Sorry for the nitpicking:

### Trailing spaces

Lines 283 and 306 have trailing spaces. Please remove these.

### Additional Reference

Please add the following reference:
https://capec.mitre.org/data/definitions/460.html

### Additional Tag

Please add the following tag:
tag:'CAPEC-460'

(We are not systematically tagging for CAPEC, but it would be useful if we would.)

### Describing the functionality of the two rules

You may want to add a sentence about the functionality of the two rules. 921170 counts
the occurrences of the individual parameters. 921180 checks if any counter is > 1.

### Matching operator in 981170

The rule uses a regex to get MATCHED_VAR_NAME. Any MATCHED_VAR_NAME. I wonder if `@rx` is not overly heavy for this simple functionality. Alternatively we could use `@gt 0` in combination with `t:length`. This is likely faster, but I am not really sure. It's probably a policy thing how we do this - here and in other spots within the ruleset.
@franbuehler : Let's hear the other ones on this point before you change anything about this matching operator.

All in all a very welcome PR with a good quality. Thank you.

**Comment by dune73** [comment]
Thank you for the update @franbuehler.

All issues fixed. I am ready to merge. Final opinions?

**Comment by csanders-git** [comment]
I think it looks good and adds a good protection, nice job @franbuehler

**Pull request merged**
