### PR TITLE
Pattern cleanup - part one

### PR DESCRIPTION
**Pull request by fgsch**
First pass at cleaning up the patterns. 
More to come.

### CODE REVIEW

**Comment by dune73** [comment]
Good works. Thanks.

Could you please explain your changes in 941350 and also the change in one of the tests for this rule?

**Comment by fgsch** [comment]
The commit for the test has an explanation (`Was using the equivalent to "<...<" instead of "<...>"`). Let me know if this is not enough. 

I will update the commit for the rule itself but basically the rule was checking the equivalent to `"<...[<>]"`, instead of `"<...>"` (same as the test).

**Comment by dune73** [comment]
That's definitely enough (Sorry, overlooked).

I take it, this is a work in progress, or do you want to merge this separately and then add a new PR?

**Comment by fgsch** [comment]
I'd like to merge the PRs separately to make things easier.

**Comment by dune73** [comment]
So ready to be merged?

**Comment by fgsch** [comment]
Let me update the commit message for the change in the rule and I will let you know.

**Comment by fgsch** [comment]
Reworded the commit to hopefully explain what I did with the rule 941350.
Let me know if this makes sense.

**Comment by fgsch** [comment]
@dune73 ready for another 👀

**Comment by fgsch** [comment]
Rebased against latest v3.3/dev commit.

**Comment by dune73** [comment]
Looks good to me, thanks. Tell me if you want to have it merged.

**Comment by fgsch** [comment]
@dune73 yes, please.

**Comment by dune73** [comment]
Here we go. Thank you for this PR. Things as this are important, even if it just looks like cosmetics.

**Pull request merged**
