### PR TITLE
Fix libmodsecurity (v3) incompatible ctl:ruleRemoveByTag

### PR DESCRIPTION
**Pull request by emphazer**
according to #1418

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
thanks @emphazer 

unfortunately, it seems that ruleRemoveById doesn't work properly when a range is given :( https://github.com/SpiderLabs/ModSecurity/issues/2099#issuecomment-494046423 this makes useless a lot of CRS exclusion rules when using on libmodsecurity (v3).

**Comment by emphazer** [comment]
okay @theMiddleBlue 
i will fix that

**Comment by emphazer** [comment]
@theMiddleBlue but that will fix just a part of the problem.
they must fix it in libmodsecurity or else we can't keep this rule exclusions in my opinion.

**Comment by theMiddleBlue** [comment]
thanks! 

> they must fix it in libmodsecurity

yes, they must. Our exclusion rule set makes extensive use of `ruleRemoveById` with ranges and `ruleRemoveByTag`. This makes CRS incompatible with the current v3... I'm waiting for an answer here https://github.com/SpiderLabs/ModSecurity/issues/2099

**Comment by theMiddleBlue** [comment]
A PR will be soon available on ModSecurity in order to fix this. Thanks!

**Comment by theMiddleBlue** [comment]
fixed by https://github.com/SpiderLabs/ModSecurity/pull/2102 (thanks @airween @zimmerle)

**Pull request closed without merging**
