### PR TITLE
Correct escaping

### PR DESCRIPTION
**Pull request by fgsch**
You don't need to escape \ between \Q and \E.

### CODE REVIEW

**Comment by fgsch** [comment]
This is work in progress. Ignore for now.

**Comment by fgsch** [comment]
Testing with pcretest:
```
  re> "\Q\\Efoo"
data> \\foo
 0: \foo
data>
  re> "\Q\\\Efoo"
data> \\foo
No match
data> \\\\foo
 0: \\foo
```

**Comment by fgsch** [comment]
Need to investigate why the test is failing (with or without this patch).

**Comment by dune73** [comment]
Thank you for taking care of this.

**Comment by fgsch** [comment]
I found why the test is failing so I will open a separate PR to deal with it, and this will concentrate on the rule itself.

**Comment by fgsch** [comment]
Closing for now. Will reopen when I have an update.

**Pull request closed without merging**
