### PR TITLE
Catch GET or HEAD with Transfer-Encoding

### LINKED ISSUE #909: Possible bypass using GET/HEAD with Transfer-Encoding
As per https://tools.ietf.org/html/rfc7230#page-28:

```
   The presence of a message body in a request is signaled by a
   Content-Length or Transfer-Encoding header field.  Request message
   framing is independent of method semantics, even if the method does
   not define any use for a message body.
```

Rule 920170 deals with Content-Length. We should handle T-E as well.

### PR DESCRIPTION
**Pull request by fgsch**
Sibling of rule 920170.

Fixes #909.

### CODE REVIEW

**Comment by spartantri** [comment]
:+1:

**Comment by csanders-git** [comment]
i'll take a look at this today see if we can get it merged

**Comment by csanders-git** [comment]
Thoughts on adding tests for this 

```
---
  meta: 
    author: "csanders-git"
    enabled: true
    name: "920171.yaml"
    description: "A Selection of tests to trigger rule 920171"
  tests: 
    - 
      # POST Request with data (valid)
      test_title: 920171-1
      stages: 
        - 
          stage: 
            input:
              dest_addr: "127.0.0.1"
              method: "POST"
              port: 80
              headers:
                  User-Agent: "ModSecurity CRS 3 Tests"              
                  Host: "localhost"
                  Content-Type: "application/x-www-form-urlencoded"
              data: "hi=test"
              uri: "/"
            output: 
              no_log_contains: "id \"920171\""
    - 
      # GET request with data
      test_title: 920171-2
      stages: 
        - 
          stage: 
            input:
              dest_addr: "127.0.0.1"
              method: "GET"
              port: 80
              headers:
                  User-Agent: "ModSecurity CRS 3 Tests"              
                  Host: "localhost"
                  Transfer-Encoding: chunked
              uri: "/"
            output: 
              log_contains: "id \"920171\""      
    - 
      # Head Request with data
      test_title: 920171-3
      stages: 
        - 
          stage: 
            input:
              dest_addr: "127.0.0.1"
              method: "HEAD"
              port: 80
              headers:
                  User-Agent: "ModSecurity CRS 3 Tests"              
                  Host: "localhost"
                  Transfer-Encoding: chunked
              uri: "/"
            output: 
              log_contains: "id \"920171\""
    - 
      # GET Request but content length is 0 and data is provided
      # Weird HTTP 1.0 support bug in Apache, without newline causes 408
      test_title: 920171-5
      stages: 
        - 
          stage: 
            input:
              dest_addr: "127.0.0.1"
              method: "GET"
              port: 80
              headers:
                  User-Agent: "ModSecurity CRS 3 Tests # Possibly shouldn't pass"              
                  Host: "localhost"
                  Content-Type: "application/x-www-form-urlencoded"
                  Transfer-Encoding: chunked
              data: "hi=test\r\n"
              stop_magic: true
              protocol: "http"
              uri: "/"
            output: 
              log_contains: id "920171"      
```

**Comment by fgsch** [comment]
Might be worth having real data in there.
Not sure I understand the last one though?

**Comment by csanders-git** [comment]
Always support real data if you have it!!!
stop_magic prevents it from sending a content-type header but it still sends a Transfer-Encoding.

**Comment by fgsch** [comment]
I mean neither the HEAD nor GET specify any data. Is this not supported by ftw?

I understand what stop_magic does, my question is why are you sending non-chunked data with a chunked encoding and why would Content-Lenght be 0?

**Comment by csanders-git** [comment]
Ahh it supports it, i just made a bunch of random tests to make sure that the rule was firing in strange situations :)

**Comment by dune73** [comment]
Should the tests be merged into this PR before merging the PR. 

Otherwise, what's holding back a merge? 

It looks good to me.

**Comment by csanders-git** [comment]
I guess it depends, currently we have no strict requirement for them so it's up to @fgsch :)

**Comment by fgsch** [comment]
I'd like to get this in first. 

I'm happy to work on some tests afterwards, or we can use what @csanders-git proposed, either way is fine.

**Comment by dune73** [comment]
Thanks, guys. So it's ready for merge?

Actually, @csanders: I still can't get FTW to work (see separate mail exchange). And @franbuehler and I would probably like to use it on Friday for the DINACon Hacknight.

**Comment by fgsch** [comment]
@dune73 from my POV is good to go.

**Comment by dune73** [comment]
Merging. Thank you for the contribution @fgsch.

**Pull request merged**
