### PR TITLE
Travis failure workaround

### PR DESCRIPTION
**Pull request by theMiddleBlue**
It seems there's a problem with the docker image used by Travis to run apache + modsec (https://hub.docker.com/layers/owasp/modsecurity/2.9-apache-ubuntu/images/sha256-21346781341f6dac40212101726f2cabee2d711315c3c18170cd7bf156fe58a2 by @bittner).

With this image all test pass but I can't figure out why it happens... any help would be appreciated.

### CODE REVIEW

**Comment by franbuehler** [comment]
Well done @theMiddleBlue !! Great you found the problem!

**Comment by bittner** [comment]
Is there a specific reason why you add the `.travis.yml.bkp` file?

**Comment by theMiddleBlue** [comment]
> Is there a specific reason why you add the `.travis.yml.bkp` file?

Absolutely not. removed.

**Comment by bittner** [comment]
Do you have an example of a failing build with the [owasp/modsecurity-crs](https://hub.docker.com/r/owasp/modsecurity-crs/tags) image?

The idea would be that you mount the CRS rules into the container. So, in contrast to the current process where we build the image entirely to include the rules we want to test, we would always use a production-grade image from Docker Hub and only inject the (latest) CRS rules.

Does that make sense?

**Comment by theMiddleBlue** [comment]
[here you can find a failed test](https://travis-ci.org/SpiderLabs/owasp-modsecurity-crs/jobs/647489327?utm_medium=notification&utm_source=github_status). If you mean the "docker image build" by Travis, it works fine but the FTW test fails in an unexpected way and we can't figure out why...

**Comment by bittner** [comment]
There should be no
```
docker build ...
```
anymore in the CRS test suite in future, only
```
docker run -v $(pwd):/opt/owasp-crs owasp/modsecurity-crs
```
(similar to what you do in this PR), which would mount this repository, and hence the CRS rules to be tested, into the running container.

**Comment by bittner** [comment]
The [error in the build](https://travis-ci.org/SpiderLabs/owasp-modsecurity-crs/jobs/647489327#L2948-L2990) you mention seem like actually being a `HttpResponse` not containing a gzipped file (as the error message indicates). That could be a non-existing object, e.g. an error 404, for some reason.

Has anyone tried to remove a few of the YAML files from the test suite to see whether the error continues to occur at the same YAML file, maybe?

### Python 2.7

As a side note, the test suite is still running on Python 2.7 (I know, this is probably unrelated to the issue at hand). That will cause harm in the long run. It will be a good idea to move on to Python 3.6+ (which is also faster).

**Comment by dune73** [comment]
Thank you @bittner. We are aware of the python 2.7 situation. Tests showed yesterday that it's not the cause here. I also suggested a reduction to the failing test and in order to debug it faster / easier. But meanwhile @theMiddleBlue has provided this workaround, which could serve us short term.

The PR queue is clogged due to the Travis failure now.

In the separate slack channel "crscontainer" @fzipi has proposed something very similar to what you mentioned above for future testing, I think. Would you mind casting an eye on that?

**Comment by theMiddleBlue** [comment]
> Has anyone tried to remove a few of the YAML files from the test suite to see whether the error continues to occur at the same YAML file, maybe?

yes, we tried and we got the same error. But, as you can see, the problem is not on tests. It should be something related to the apache or the docker image itself (since all tests pass with my docker image apache+modsec2.9).

**Comment by dune73** [comment]
Okidoki. So let's get this sucker merged and see what happens to the other PRs.

Thank you for your time, @theMiddleBlue.

**Pull request merged**
