### PR TITLE
[1060] Add PL1 tag

### PR DESCRIPTION
**Pull request by annawinkler**
Per issue https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1060, add `paranoia-level/1` tag to those rules.

### CODE REVIEW

**Comment by csanders-git** [comment]
I see no issue with this merge any thoughts @dune73

**Comment by airween** [comment]
> I see no issue with this merge any thoughts @dune73

See #1060 :)

**Comment by airween** [comment]
Let me check this with parser before merge.

**Comment by csanders-git** [comment]
Can we inline the parser into Travis?

**Comment by csanders-git** [comment]
Also feel free to merge once you check

**Comment by airween** [comment]
> Can we inline the parser into Travis?

Yes, that's on my todo list - coming soon :)

**Comment by airween** [comment]
@annawinkler thanks for your patch. I reviewed the modifications with the parser, but I'm afraid there are some missed `tag` - see this [table](https://docs.google.com/spreadsheets/d/1TT0G1nEesz-a16cUQHwVVG4wjGDhRX1CTIDfocsQRTI/edit#gid=1268524867). You can turn on the filter and can see only the rows with value 0 in column 'L'. (There couldn't be any row with value 0 in this column.)

Here are the rules:
[912120](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L104)
[912130](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L125)
[912140](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L145)
[912150](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L161)
[912160](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L190)
[912161](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L207)
[912170](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L229)

Those rules also activated at PL1, see the [setter line](https://github.com/annawinkler/owasp-modsecurity-crs/blob/f81e23876ff70f30d5179130dff5040c5741faea/rules/REQUEST-912-DOS-PROTECTION.conf#L91).

If you're done, just check your modifications with the given script, which generates the new table. Don't forget to re-build the structure from the modified rules before (with command `crs_read.py`). Then you can check that everything is well. If you have any question, just let me know :).

**Comment by annawinkler** [comment]
Thank you for checking this PR @airween! I'll add those rules and double-check per your comment.

**Comment by fgsch** [comment]
Hi @annawinkler. Are you planning to update this soon~ish or should we consider merging it as is and tackle the remaining rules in a separate PR?

**Comment by airween** [comment]
I think the separated PR could lead to misunderstanding in this case (if somebody review the commits few mounts later).

**Comment by annawinkler** [comment]
Sorry for the delay friends! I'll work on this today.

**Comment by annawinkler** [comment]
@fgsch and @airween I updated the rules and ran airween's script to verify the `PL tag correct` value in the generated csv file (generated from yaml from the rules). I do not see any `0` values, so I think all of the rules that should be tagged PL1 are. Could you please confirm and let me know? Thanks!

**Comment by airween** [comment]
Nice work @annawinkler, thank you!

**Pull request merged**
