### PR TITLE
Add AngularJS client side template injection

### PR DESCRIPTION
**Pull request by franbuehler**
This is a new rule 941370 at PL1.
This PR covers client side template injection with AngularJS.
Angular and AngularJS are executed in the client browser and are not detected by CRS. But as soon as a command is sent to the server, we should detect the injection.
That this traffic is sometimes sent to the server, I have seen in the intentionally vulnerable app Pixi by DevSlop.

I am not sure about false positives. I would be happy if someone could test this PR ;)

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for the PR.

While writing `{{...}}` is rather unnatural, I think PL1 might be a bit optimistic...

**Comment by fgsch** [comment]
Tests are failing:

```
util/integration/format_tests.py::test_trailing_whitespace Line 721 in ./rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf has trailing whitespace.
```

**Comment by fgsch** [comment]
Can you sync with master so this is testing against the right image?

**Comment by dune73** [comment]
We have not seen any real world tests of this rule and I am reluctant to merge at PL1. Would merge at PL2 though. For PL1, I think we need reports about the rate of FPs.

**Comment by franbuehler** [comment]
This PR could also be reviewed again, please.

**Comment by dune73** [comment]
@franbuehler : Thank you for the update. It has a conflict now. Can you fix that?

**Comment by dune73** [comment]
Thank you for the updates.

**Comment by dune73** [comment]
Seems to be ready to go. Thank you for the PR. Merging now.

**Comment by emphazer** [comment]
@franbuehler @dune73 
i recommend to remove XML matching

**Pull request merged**
