### PR TITLE
fix ReDoS condition found by rcbarnett

### PR DESCRIPTION
**Pull request by jnazarioFastly**
addresses #153

### CODE REVIEW

**Comment by jnazarioFastly** [comment]
after this change:

	INPUT: /(?i:(?:[%22'`]\s+and\s*?=\W)|(?:\(\s*?select\s*?\w+\s*?\()|(?:\*\/from)|(?:\+\s*?\d+\s*?\+\s*?@)|(?:\w[%22'`]\s*?(?:(?:[-+=|@]+\s+?)+|[-+=|@]+)[\d(])|(?:coalesce\s*?\(|@@\w+\s*?[^\w\s])|(?:\W!+[%22'`]\w)|(?:[%22'`];\s*?(?:if|while|begin))|(?:[%22'`][\s\d]+=\s*?\d)|(?:order\s+by\s+if\w*?\s*?\()|(?:[\s(]+case\d*?\W.+[tw]hen[\s(]))/
	PARSE: OK
	SIZE: 169
	PUMPABLE: NO
	TIME: 0.000329 (s)
	>> TOTAL: 1
	>> PARSED: 1
	>> MAX NFA SIZE: 169
	>> AVG NFA SIZE: 169
	>> PUMPABLE: 0
	>> VULNERABLE: 0
	>> INTERRUPTED: 0
	>> PRUNED: 0
	>> TIME TOTAL: 0.000329 (s)
	>> TIME MAX: 0.000329 (s)

**Comment by dune73** [comment]
This fixes the problem for CRS2.2.X. It is still not addressed in CRS3 (-> rule 942310), where the regex has been enhanced a bit in the meantime.

@lifeforms: I think the milestone tag is misplaced. Or is it meant as a reminder, we need to fix this for 942310?

**Comment by lifeforms** [comment]
@dune73 I just wanted to make sure we would look at this in time, even if we decide to not fix it in CRS3.

**Comment by dune73** [comment]
@lifeforms: PR for CRS3 in #605. Please check the regex.

**Comment by csanders-git** [comment]
Seems to be the same fix I tested this in 3.x I'm pretty comfortable with merging in 2.x unless anyone has any objections

**Comment by dune73** [comment]
Thank you @jnazarioFastly.

**Pull request merged**
