### PR TITLE
Update travis to support secrules parsing

### PR DESCRIPTION
**Pull request by csanders-git**
We are using a variation of the script provided earlier to provide basic syntax checking, but this script could be expanded to really do any advanced level checking needed.

### CODE REVIEW

**Comment by fgsch** [comment]
Looks good to me.

I'd probably check the syntax before running the tests (as the tests take longer) but your call.

**Comment by csanders-git** [comment]
I'll switch it and merge today

**Comment by fgsch** [comment]
@csanders-git Let me know if you need help with this so we can merge it.

**Comment by dune73** [comment]
Monthly chat: @csanders-git is reordering and will merge afterwards.

**Comment by csanders-git** [comment]
closing to rebase more easily

**Pull request closed without merging**
