### PR TITLE
Remove req msg dot

### LINKED ISSUE #1622: Inconsistent style in rule names
## Type of Issue
Cosmetic

## Description
Some rules name finish with a dot, while others don't.
Should be unified one way or another.

### PR DESCRIPTION
**Pull request by nerrehmit**
This fixes #1622 by removing all the trailing dots in the `msg` action. 

It can be verified by comparing the google [docs](https://docs.google.com/spreadsheets/d/1jwBkFWIhuOThsBFXOCi8QReZpIjVxXLZ8QQNtwffDGo/edit?usp=sharing) with the messages before the change and [after](https://docs.google.com/spreadsheets/d/1uLiG8mJ4sBYswA8g6TAogpcv5PzeEtRUKLhQgxHzrqU/edit?usp=sharing)
Thanks to @airween for patiently explaining msc_pyparser to me and writing a python script to find all the msg dot actions in the referenced issue.

### CODE REVIEW

**Comment by nerrehmit** [comment]
I don't know if we would want to prevent `msg` actions with a trailing dot in the future by some kind of automated tests? I have no idea if this is possible and if so how to go about it.

**Review by airween — APPROVED** [review]

**Comment by airween** [comment]
LGTM - thanks @nerrehmit.

**Comment by airween** [comment]
> I don't know if we would want to prevent `msg` actions with a trailing dot in the future by some kind of automated tests? I have no idea if this is possible and if so how to go about it.

I started to work on a CRS testing [utility](https://github.com/airween/secrules_check), but I think the concept (in this form) is not well. We need to re-think this process, and may be first time only to propose for the developers in documentation. Otherwise, there are so many idea what we can check automatically - see the example/ dir of msc_pyparser.

**Comment by fgsch** [comment]
Looks good. 

One small nitpick: can you also update the commented out rule in REQUEST-910-IP-REPUTATION.conf?

> \#   msg:'Client IP in Trustwave SpiderLabs IP Reputation Blacklist.',\

**Comment by nerrehmit** [comment]
Thank you @fgsch for noticing. I updated the rule you mentioned and verified with `grep -ir 'msg:'.*'\.'` that this was the only instance of it's kind.

**Comment by dune73** [comment]
Thank you for the welcome PR @nerrehmit. Travis is failing, but that's not your problem. It's ours.

Also: We shifted the monthly chat by a week. So this will happen on Monday 2030 MET. I'd love to see you in the chat too.

**Comment by dune73** [comment]
Meeting decision: Will be merged once Travis works again.

https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1671#issuecomment-584320407

**Comment by dune73** [comment]
Thank you for the update. I looked through the additional commits and everything seems in order.

Merging now.

**Pull request merged**
