### PR TITLE
Fixing bug in 912160 (dos_burst_counter jumping from 0 to 2)

### PR DESCRIPTION
**Pull request by dune73**
This PR fixes an old issue in the anti-ddos rules. It incorporates a fix by @loudly-soft proposed in issue #346.

### CODE REVIEW

**Comment by dune73** [comment]
I do not want to merge my own stuff without further review. Could somebody please take a look?

**Comment by csanders-git** [comment]
@dune73 i'm gonna be testing as many of these as I can today.

**Comment by lifeforms** [comment]
Discussion on IRC: @franbuehler and @lifeforms will do a quick test if DDoS checks are working well, if so will merge for 3.0.1.

**Comment by lifeforms** [comment]
Tested successfully here, so OK to merge as far as I am concerned.

I get succesfully blocked when requesting too fast. In fact it now blocks correctly at `dos_counter_threshold` + 1 requests. Used to take `dos_counter_threshold` + 2 requests.

**Comment by franbuehler** [comment]
I will do some tests today.

**Comment by franbuehler** [comment]
The faulty behaviour (`dos_burst_counter` set from 0 to 2) is gone. The `dos_burst_counter` is no longer raising to higher values than 2.
With a low volume of concurrent requests the behaviour is good:
The `dos_burst_counter` is now raised after `dos_counter_threshold` requests (now `"@ge %{tx.dos_counter_threshold}"`, not `@gt` anymore). That makes sense.
With a lot of concurrent requests the behaviour is not so clear anymore: the `dos_burst_counter` is sometimes raised after `dos_counter_threshold + 4` or even more requests.
As far as I understand this behaviour under a lot of concurrent requests is not avoidable. But we now have no blocked legitimate requests anymore, but maybe some requests which get through, because they were blocked a bit too late.

The false positives are gone and the PR works as intended.

**Comment by dune73** [comment]
That's a very detailed analysis. Thank you very much. Yes, I think this is as far as we can get with our technique. It has its limits, but small and simple application layer DoS attacks will be caught and mitigated.

**Comment by dune73** [comment]
Thank you @lifeforms.

**Pull request merged**
