### PR TITLE
Fix broken regex in 2011256

### PR DESCRIPTION
**Pull request by p0pr0ck5**
Regex contained a '+' following a non-quantifiable group (specifically,
the opening case-insensitive non-capture marker).

Fixes issue #259.

### CODE REVIEW

**Comment by csanders-git** [comment]
Thanks for your pull, sorry it took so long to review it. Be sure that you are checking out the v3.0.0-dev branch of CRS for better rules

**Comment by p0pr0ck5** [comment]
Is this not going to be merged? Right now the broken regex prevents Apache from loading.

**Comment by csanders-git** [comment]
Apologies... thought i merged it but i hit the wrong button... nice commit ;)

**Comment by p0pr0ck5** [comment]
No worries, thanks! I had initially thought you were ignoring it and only focusing on v3 rules moving forward. Looking forward to further work on this!

**Comment by csanders-git** [comment]
we are focusing on v3 rules but that doesn't mean the community has to :)

**Pull request merged**
