### PR TITLE
Remove all trailing spaces from ftw yaml test files

### PR DESCRIPTION
**Pull request by airween**

### CODE REVIEW

**Comment by fgsch** [comment]
LGTM.

Adding `?w=1` to the url when looking at the files confirms this PR is only compromised of whitespace changes.

**Comment by airween** [comment]
Sorry, adding `?w=1` to which url?

**Comment by fgsch** [comment]
`https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1559/files`

**Comment by airween** [comment]
Oh, it's magic! :)

Thanks!

**Pull request merged**
