### PR TITLE
V3.0.0 dev

### PR DESCRIPTION
**Pull request by shimshon70**
1. Adding full-width less than and greater characters to rule 973336.
2. False positive for rule 973338. Adding word boundary checks.

### CODE REVIEW

**Comment by csanders-git** [comment]
hey @shimshon70 do these fixes still apply to the v3.0.0-rc3 branch? This dev branch is historical in nature at the moment. It is left up for people who are still using it.

**Comment by shimshon70** [comment]
I am working with dev3.0.0.  branch because my building issues,  but merging rc3 diffs.
Anyway, these two pulls are still relevant for rc3

**Comment by csanders-git** [comment]
Is there a reason you closed this? I reponed it.

**Comment by dune73** [comment]
@csanders-git : How do we pull this into rc3?

**Comment by csanders-git** [comment]
@dune73 fortunately this is just a really clever XSS obfuscation. I think we should be able to merge this with minor changes by tmrw, I'll take over testing to ensure it's completion @shimshon70 any chance you have some samples that will trigger your new variant - maybe a back story about it :) -- it is neat.

**Comment by lifeforms** [comment]
Uuuurghhh, do browsers/servers still interpret fullwidth? I remember this from a long time ago!

**Comment by csanders-git** [comment]
@lifeforms right? probably IE -- it's why i asked for examples -- god i hate the internet sometimes :)

**Comment by lifeforms** [comment]
@csanders-git ＩＴ＇Ｓ  ＡＬＷＡＹＳ  ＩＥ

**Comment by shimshon70** [comment]
I created [#636](https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/636) on rc3 branch.
it has some examples. let me know if it is clear.
regarding full-width, it is IE11

**Comment by csanders-git** [comment]
@shimshon70 so about moving away from the dev branch... are you planning on doing that? we were going to remove it soon. replace it with a v3.0.x/dev

**Pull request closed without merging**
