### PR TITLE
942410: fixing broken regex

### PR DESCRIPTION
**Pull request by dune73**
This solves issue #700.

Fixing the following keywords in the regex:
- sp_sp_replwritetovarbin -> sp_replwritetovarbin
- sp_sp_help -> sp_help
- sp_sp_password -> sp_password
- xp_xp_servicecontrol -> xp_servicecontrol
- xp_xp_ntsec_enumdomains -> xp_ntsec_enumdomains
- xp_xp_terminate_process -> xp_terminate_process

### CODE REVIEW

**Review by whuben — APPROVED** [review]
that's it, good!

**Comment by dune73** [comment]
Thank you for the confirmation, @whuben.

**Comment by csanders-git** [comment]
i'm going to try and come up with more regression tests for this also

**Comment by lifeforms** [comment]
I verified that the change contained just the removal of three superfluous `sp_` and `xp_` prefixes deep in the regexp, and did some cursory HTTP requests to verify. Nice fixing and also nice find anyway by @whuben !

**Comment by dune73** [comment]
Thanks for the merge, @lifeforms. We're slowly getting closer to 3.0.1.

**Pull request merged**
