### PR TITLE
Update CONTRIBUTORS

### PR DESCRIPTION
**Pull request by theMiddleBlue**

### CODE REVIEW

**Comment by dune73** [comment]
Would you mind moving your entry after Victor Hora. There is actually alphabetical order on the surname.

**Comment by theMiddleBlue** [comment]
ops

**Comment by dune73** [comment]
Thank you. I'm overriding the Travis failure and merging this. Welcome to the team.

**Comment by lifeforms** [comment]
(Now officially) welcome @theMiddleBlue!

**Pull request merged**
