### PR TITLE
SQLi: move 'HAVING injections' to PL3

### PR DESCRIPTION
**Pull request by lifeforms**
Fixes false positives from detecting `HAVING` SQLi injections (see #409).

On the dataset of 126k Reddit comments, rule 942250 (Detects MATCH AGAINST, MERGE, EXECUTE IMMEDIATE and HAVING injections) matched 2142 times (1.7%). Rule 942250 is now the biggest source of false positives on that dataset (after rule 932100 was reworked). Even a string like `I am having trouble` matches this rule.

The `HAVING...` part of rule 942250's regexp looks to be somewhat redundant, since libinjection (rule 942100) also catches HAVING syntax. All sqlmap traffic that hit this rule had score 20. So the pattern might be safe to move to higher levels.

After splitting this part off to rule 942251 at PL3, all the false positives from this rule on the Reddit dataset are gone!

### CODE REVIEW

**Comment by csanders-git** [comment]
I'm going to convert your unit tests and then this is next up to bat. Any additional ones not merged in that you want to hand over?

**Comment by lifeforms** [comment]
@csanders-git I have lots of loose things lying around that depend on paranoia levels, but I don't think WTF can set those, right? So for the time being no thank you!

**Comment by dune73** [comment]
This looks good to me @lifeforms.

One documentation issue. With the stricter sibling, I tried to stick to the convention, that all strict siblings start with a comment as follows:

```
#
# This is a stricter sibling of rule 942430.
#
```

You are basically saying the same in other words. Would you mind following the convention?

**Comment by lifeforms** [comment]
@dune73 Is it really a sibling though? It's not a question of copying an existing rule and adjusting its toughness; I split one rule in two totally different rules. But if you want, it's fine with me.

**Comment by dune73** [comment]
Interesting thought @lifeforms.

I think it is a "sibling" as the rules are clearly related.

I also think it is "stricter" in the sense, that it applies a similar / sibling pattern which generates more alerts than the PL1 rule.

But is it also a "stricter sibling"? We used the term for "the same rule but stricter limits". In the validateByteRange PR #435, I called the rule 920274 a stricter sibling even it is closer to the case here. So I think we should use a broad definition of stricter sibling for rules which share the same idea or mechanism. Especially when the sibling runs on a different PL.

Does this make sense?

**Comment by lifeforms** [comment]
Comment added.

The rules are not really that related any longer though. The old rule matches the following strings:
```
merge using (1 2 3)
execute immediate 'foo'
match (foo) against (foo)
```

The new one matches stuff like:

```
1 having 1
1 having 1=1
1 having id=id
I am having trouble -.-
```

**Comment by dune73** [comment]
Thanks. One day we will write a clear description, what a strict sibling is. Initially it was very clear for me. Now seeing things clearer the rules have all sorts of interesting relationships.

**Comment by dune73** [comment]
Thanks fixing this FP issue with HAVING.

**Pull request merged**
