### PR TITLE
Drop revision

### PR DESCRIPTION
**Pull request by fgsch**
This is the result of `sed -i '' '/rev:/d' *.conf` so we can regen at any time.

Addresses #1116

### CODE REVIEW

**Comment by dune73** [comment]
Tested. Ready to be merged. Thank you for such a fast PR.

**Comment by lifeforms** [comment]
Probably spurious, but please merge only after other PRs have closed.

**Comment by dune73** [comment]
As we said in the chat.

**Comment by fzipi** [comment]
LGTM

**Comment by csanders-git** [comment]
waiting for the hybrid paranoia mode and content type merges.

**Comment by csanders-git** [comment]
waiting on the content type merge so that this one becomes mergeable

**Comment by csanders-git** [comment]
This is now ready!!!

**Pull request merged**
