### PR TITLE
Fixes for RESPONSE-999 documentation and example issues (as seen in #648)

### PR DESCRIPTION
**Pull request by csanders-git**
Adding fixes for comments within RESPONSE-999 that incorrectly referenced local files after some name changes. Also fixed various examples that referenced old method of adding exceptions with chains when using a chained rule as indicated in #648

### CODE REVIEW

**Comment by dune73** [comment]
This looks good. Thank you.

But v3.0/dev is behind with regards to v3.0/master. So merging can not yet be performed.

**Comment by csanders-git** [comment]
Whats not up to date?

**Comment by dune73** [comment]
It's like 6 or 8 commits behind.

**Comment by csanders-git** [comment]
let me pull that in :-X

**Comment by dune73** [comment]
Thank you.

**Comment by dune73** [comment]
Looks very good. Thank you.

**Pull request merged**
