### PR TITLE
Increasing range header

### PR DESCRIPTION
**Pull request by emphazer**
according to https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/499

### CODE REVIEW

**Comment by dune73** [comment]
Thank you @emphazer. Looks good.

Will you do a separate PR for 3.1 or how do we handle that?

**Comment by emphazer** [comment]
@dune73 
Sure, i did it here https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/867
I hope it's okay.

**Review by dune73 — APPROVED** [review]
Implements change as discussed in reopened issue  and in monthly chat.

**Comment by dune73** [comment]
Ready to merge. Opposing views?

**Pull request merged**
