### PR TITLE
Update Tags to be more unified as specified in #383

### PR DESCRIPTION
**Pull request by csanders-git**
Specified in #383
Some small changes were made to the overall suggestion in or to maintain ease of use for automated scripts. That is retaining the prefix 'attack' in front of reputational data. Additionally I removed IP_REPUTATION/MALICIOUS_CLIENT type tagging as it was redundant and didn't really add anything in most cases.

### CODE REVIEW

**Comment by csanders-git** [comment]
There was no decision on what to do with things labeled like: OWASP_CRS/POLICY/HEADER_RESTRICTED which are used as part of anomaly scoring and might be removed in the future depending on further conversation.

**Comment by dune73** [comment]
I love this initiative. I always thought the tagging was so chaotic. Much better now.

I have looked at the changeset in detail. But I have not tested it. Plan to do so soon.

**Comment by lifeforms** [comment]
+1 from me! Nice job on `platform-iis` and `attack-fixation`.

**Comment by csanders-git** [comment]
It's small enough that having just one person @lifeforms look it over makes me feel comfortable ... merged.

**Pull request merged**
