### PR TITLE
Fixed "unknown option ff-only"

### PR DESCRIPTION
**Pull request by mtrimarchi**
This commit fix this error:
crs: Git pull failed! Error: error: unknown option `ff-only'

### CODE REVIEW

**Comment by csanders-git** [comment]
This is fixed in v3.1/dev already,  do you find that you use this script? there was conversation about removing it all together.

**Comment by mtrimarchi** [comment]
Woah, I've found this issue today on a debian vm. If it's a known bug, why this has not been already patched on v3.0/master?

**Comment by csanders-git** [comment]
v3.0/master is a release. v3.0/dev is the current tracking development. The bug was not considered large enough for a release.

**Comment by mtrimarchi** [comment]
Ok, now I got it. So, I can close this PR right now ;)

**Pull request closed without merging**
