### PR TITLE
Initial functionality for easing in

### PR DESCRIPTION
**Pull request by dune73**
This is based on issue #410.

I was able to reduce the hackyness of the rnd approach by using the correct transformation before accessing the UNIQUE_ID hash. This reduces the complexity a lot. I also simplified the whole rnd generation process.

All the sampling is skipped if we are at a sample percentage of 100. If we decide to bypass the ruleset, the ruleegine is disabled (vs. the other options like skipping the whole ruleset or removing all the rules by id range).

### CODE REVIEW

**Comment by lifeforms** [comment]
I tested this and liked the randomness! This will be very cool.

A few comments!

1. When introducing a new setting, we should make it 'fail safe'. Right now, if the `tx.sampling_percentage` is undefined, the whole CRS will be skipped, which could be disastrous. This might happen if a person uses an old setup.conf (remember, we update the .example but not necessarily the user's production copy). Another reason could be a person naively commenting out the variable (thinking this might disable the sampling). Right now we might be in the situation to tell everybody 'delete your setup.conf and start over', but why not get into best practices? So I would recommend just adding a fail-safe rule such as the following:

```
SecRule &TX:sampling_percentage "@eq 0" \
	"id:901101,\
	phase:1,\
	pass,\
	nolog,\
	skipAfter:END-REQUEST-901-SAMPLING"
```

2. Your PR intersects with some todo items of mine. I still need to add some rules at the very start of the CRS, in order to do sanity checks. Would you mind renaming the `901` file to  `REQUEST-901-START.conf`, so that we can use it for other general setup and preparatory rules as well? Then I can just base my PR on your file instead. Another reason why I prefer a more general name is, it's dangerous to introduce new rule files after 3.0.0 right now, because Nginx/IIS users on ModSecurity 2 will have to list the files in their web server configs separately. You can guess what will happen if we add a new file later -- a certain sampling percentage of people will forget to update their configs.

**Comment by dune73** [comment]
Thank you for your review @lifeforms.

(2) Sounds good.
(1): Yes, we need such a safety net. Franziska noted we have the same issue with tx.paranoia_level, where PL4 is enabled if the variable is not set. You assign "preparatory" rules to the file `REQUEST-901-START.conf`: I see some value in introducing a section "fixing missing settings" in this file. There we could do tests as the one proposed by you, but then instead of skipping, we would set a default value - the one proposed in the setup.conf. Skipping is no problem for sampling_percentage, but we can not do the same for the paranoia-level, so I think assigning a default value is the way to go here.

**Comment by lifeforms** [comment]
@dune73 GREAT idea!

If we arranged our defaults internally, we could even make the setup example much more easy. We could just leave stuff like the sampling settings commented out by default in the example. This means that the cognitive load of learning that file will be MUCH reduced for the user. Unless they need a feature, they can just skip over it entirely, and they're also safe from accidental misconfiguration.

**Comment by dune73** [comment]
Good. I will thus rename the file to get this PR merged and allow you to add your stuff to the file.

I will then open a separate PR and start with the default value section. I assume your sanity checks will go after easing-in. The default values will go before. So your new stuff and my new PR won't conflict.

**Comment by dune73** [comment]
OK. I settled for `REQUEST-901-INITIALIZATION.conf` as filename and fixed a few typos.

Please review and merge so @lifeforms and I can continue to work on this file.

**Comment by csanders-git** [comment]
I reviewed this in the other pull.. is it different from this pull?

**Comment by csanders-git** [comment]
There is additional discussion as part of #452 ... please see that for additional detail.

**Pull request merged**
