### PR TITLE
Clean up travis and reorg

### PR DESCRIPTION
**Pull request by fgsch**
This PR reorganises things a bit, switching to an ini file for the different configs.
It also removes some unnecessary tests.

The aim here is to make the travis file easier to read and work with.

### CODE REVIEW

**Comment by csanders-git** [comment]
give me some time to review this my friend. thanks.

**Comment by fgsch** [comment]
Thanks.
Let me know if you want me to split this into multiple commits.

**Comment by csanders-git** [comment]
whats up with the ` - &test-common` stuff? is there a nice travis article i can read?

**Comment by fgsch** [comment]
That's part of yaml: https://en.wikipedia.org/wiki/YAML#Advanced_components

**Comment by fzipi** [comment]
Does it make sense to send notifications to the notify channel in slack instead of irc?

**Comment by fgsch** [comment]
@fzipi I agree but I didn't want to change the behaviour in this PR. 
Happy to update it to cover that though!

**Comment by dune73** [comment]
Thank you for volunteering to review this @csanders-git. ;)

Any news on this front?

**Comment by fzipi** [comment]
LGTM.

**Comment by csanders-git** [comment]
After reviewing the docs it looks  good - thanks for the link

**Pull request merged**
