### PR TITLE
Updating INSTALL

### PR DESCRIPTION
**Pull request by dune73**
Reflecting the changes in the rule filenames and generally rewrote the install procedure, configuration etc. Please review carefully and possibly try it out. Namely on Nginx if somebody has the time.

When doing the RC announcement we have to make people aware that the git clone proposed in the INSTALL file will give them a CRS2 until CRS3 is the new master.

### CODE REVIEW

**Comment by dune73** [comment]
Fixes #493

**Comment by dune73** [comment]
I just noticed the actual file rename for the rule exclusion files is not part of this PR. Are we doing that in a separate PR or should I update this one?

**Comment by csanders-git** [comment]
WE ought to just do it in this PR.

**Comment by dune73** [comment]
Sucks. I messed up the PR with commit 4e50cd6. Starting over.

**Comment by dune73** [comment]
See #532. Closing this.

**Pull request closed without merging**
