### PR TITLE
Hyperscan compatibility for 942450

### PR DESCRIPTION
**Pull request by allanrbo**
Problem: Hyperscan doesn't support embedded start anchors. I think it's considered embedded becuase of the + repeating the whole thing at the end.

Original expression in 2.2.0
```
(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)+
```

Original expression in 3.0
```
(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)+
```

Original expression in 3.1
```
(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)+
```

Original expression in 3.2
```
(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)+
```

Suggested rewrite
---

Remove the + at the end. There is no need for us to capture the whole thing repeated one or more times. One match is enough to trigger the rule.

Conclusion (with secrule escaping):
```
(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)
```

Testing
---
Manually on regex101.com:
```
0xdeadbeef
aaaaa0xdeadbeef
```

Automation:
```
Ran just the expected affected tests and compared results to before my change
     tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942450.yaml
```

### CODE REVIEW

**Comment by fgsch** [comment]
The problem is the \A together with the +. It is impossible to have a repetition matching at the start (in hs). In any case, the + is superfluous so LGTM.

**Comment by franbuehler** [comment]
Thank you for this PR, @allanrbo! 
LGTM!

I wondered if `[a-f\d]*` can be deleted too? 
Since it's already covered by the "unlimited" after `{3,`

**Comment by fgsch** [comment]
@franbuehler good point, we should be able to drop that as well.

**Comment by fgsch** [comment]
btw, this one too will only report a single match if we drop the +.
I think this is OK but worth having in mind.

**Comment by franbuehler** [comment]
Ok, thanks for your confirmation, @fgsch.
Then let's wait for @allanrbo's update: deletion of `[a-f\d]*`.

**Comment by allanrbo** [comment]
Good suggestion. Updated. Re-ran the 942450.yaml regression test locally.

**Comment by dune73** [comment]
Thank you for the PR, @allanrbo. I like how we drop pcre specific stuff. Merging this.

**Pull request merged**
