### PR TITLE
Fix a FP in 942360 (#1580)

### PR DESCRIPTION
**Pull request by Taiki-San**
Replace the pattern ```\s+as\s*?[\"'`\w]+\s*?from``` by ```\s+as\s+?[\"'`\w]+\s*?from``` as detailed in https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1580

### CODE REVIEW

**Comment by fgsch** [comment]
Can you update  regexp-942360.data as well since the regexp is generated from that list of patterns?

**Comment by Taiki-San** [comment]
Didn't realized, just done so!

**Comment by fgsch** [comment]
Some tests are failing. I had a look and I believe they are incorrect.
We'll need to sort them out before this can be merged.

**Comment by fgsch** [comment]
Meeting's outcome:

> Work with @emphazer to address the failing tests.

**Comment by fgsch** [comment]
@Taiki-San since you are changing this, would you mind applying a few more changes?

The pattern ```[\d\W]\s+as\b\s*?[\"'`\w]+\s*?from``` would also incorrectly match on ` as herefrom`.
Could you extend the boundary check to the `from` as well?

**Comment by fgsch** [comment]
@Taiki-San are you by any chance in the owasp slack?

**Pull request merged**
