### PR TITLE
Fix usage of invalid variables

### PR DESCRIPTION
**Pull request by victorhora**
MATCHED_VAR_NAMES is an invalid variable with ModSecurity. It should be [MATCHED_VARS_NAMES](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#MATCHED_VARS_NAMES).

This should allow CRS 3.2/dev to load cleanly with the [current version](https://github.com/SpiderLabs/ModSecurity/commit/dfbff090beda0270678343917a5be8341b5decce) of libModSecurity.

Thanks! :)

### CODE REVIEW

**Comment by dune73** [comment]
Well spotted. Thank you.

There are additional occurrences in lowercase letters. Would you mind fixing those as well?

**Comment by dune73** [comment]
Wow, I was not aware the lowercase variable names were so widespread. Thanks.

Unfortunately, you have not fixed all the occurrences of `MATCHED_VAR_NAMES`. They are all in capital letters now, but a lot still miss the `S`.

**Comment by spartantri** [comment]
wow, it's everywhere! old modsec never complained of our misspellings on this, so never really notice it until now

**Comment by victorhora** [comment]
@dune73 unless I screwed up something, both commits should result in no invalid variable names:

image

Maybe you just checked the latest commit?

**Comment by dune73** [comment]
Sorry. My bad. I saw `MATCHED_VAR_NAME` in your commit (right before going to bed).

**Comment by dune73** [comment]
Looks ready to be merged to me.

**Review by dune73 — APPROVED** [review]

**Comment by fgsch** [comment]
~IMO the fix for MATCHED_VAR_NAMES should be done separately from the case changes and backported to 3.1.~

The main issue in this PR is specific to 3.2. Sorry for the noise.

**Comment by fzipi** [comment]
I managed to reapply this PR on top of 1214, in the new #1229 . Also, backported to v3.1/dev in #1233.

Sorry @victorhora for me being to eager in merging 1214, and thanks for this one.

**Comment by franbuehler** [comment]
Closing this PR without merging because of @fzipi PR #1229.
Thank you @victorhora for finding these variables and for writing this PR!

**Pull request closed without merging**
