### PR TITLE
Known bugs rc2

### PR DESCRIPTION
**Pull request by dune73**

### CODE REVIEW

**Comment by csanders-git** [comment]
Looks good to me, ready to merge from my perspective.

**Comment by dune73** [comment]
Let's hear @lifeforms. Maybe he has something else to add before we merge.

**Comment by lifeforms** [comment]
Looks good, I will add a workaround for the Apache 2.4.11 issue using my script from #610 tonight.

**Comment by lifeforms** [comment]
Okay, I did a clean install of Ubuntu 14.04 + Apache 2.4.7 and reproduced the bug. My lil python script fixes it. I'll add it to this PR and make a note in known bugs.

**Comment by dune73** [comment]
Awesome.

**Comment by lifeforms** [comment]
Added the workaround. It's tested on Ubuntu 14 LTS.

**Comment by dune73** [comment]
Ready to merge.

**Pull request merged**
