### PR TITLE
Explicitly ignore the user defined rules

### PR DESCRIPTION
**Pull request by Everspace**
Allow git to do the work for us.

### CODE REVIEW

**Comment by csanders-git** [comment]
This looks good, would you mind merging against 3.1/dev branch and i'll cherrypick it over to 3.0/dev

**Comment by csanders-git** [comment]
If you're unsure of how to do this, I can also help you out :-)

**Comment by csanders-git** [comment]
@Everspace If you don't have time i'm more than happy to replicate this work on the 3.1 branch for you. Thank you.

**Comment by Everspace** [comment]
Sounds good, I've been rather pre-occupied.

**Comment by csanders-git** [comment]
Closing this in favor of the v3.1 commit.

**Pull request closed without merging**
