### PR TITLE
Nextcloud client support and several other modifications.

### PR DESCRIPTION
**Pull request by emphazer**
i added the possibility to view source code and to download sql files for example.
i also added support for shared writable content (public.php)

### CODE REVIEW

**Comment by fzipi** [comment]
Seems good to me!

**Comment by spartantri** [comment]
looks good, this is a looong list of exclusions

**Comment by dune73** [comment]
Wow, you are making some progress here, @emphazer. Will there be much more?

**Comment by emphazer** [comment]
@dune73 
ok, im done now.
was not much FP the past 2-3 days.

**Comment by dune73** [comment]
Hello @emphazer, just to get this right, this is now aimed at nextcloud and we need to expect a similar amount of FPs on owncloud?

**Comment by emphazer** [comment]
No no, don't worry. That was for nextcloud & owncloud and a couple of different webdav clients. In my eyes this is 98% enterprise now :-)

**Comment by dune73** [comment]
Thank you for the PR, @emphazer. We decided to merge this during the april community chat.

**Pull request merged**
