### PR TITLE
2nd attempt for the ddos cleanup and stricter sibling

### PR DESCRIPTION
**Pull request by dune73**
This is an updated remake of pull #335.

This takes in @lifeforms feedback. It seems I did not notice I broke the functionality thanks to working without the example-setup.conf locally; using my own version of the said file ;(

This is a new pull request as I seem to have killed my repository trying to update the former pull request.

### CODE REVIEW

**Comment by csanders-git** [comment]
is this ready for testing?

**Comment by dune73** [comment]
Absolutely. @lifeforms tested it. I did too.

**Comment by lifeforms** [comment]
@csanders-git One thing to test: I noted a problem with the earlier version, which might be part of a more structural issue. I've opened #364 so that discussion won't dilute this PR, but don't miss it, cause it might affect this PR too.

**Comment by dune73** [comment]
This was getting old again and the changeset was leading to conflicts. Attempted to resolve, but it seems easier to start new PL. Again. ;)

**Pull request closed without merging**
