### PR TITLE
Update examples to match the current cleanup

### PR DESCRIPTION
**Pull request by fgsch**
o Use numbers with the phase action.
o Split actions across multiple lines.

Related to #808

### CODE REVIEW

**Comment by fzipi** [comment]
Updating should solve this problem.

**Comment by dune73** [comment]
Yes, that should be simple. But it's true that all these cleanup PRs interfere with one another...

**Comment by fgsch** [comment]
Which problem, sorry?

**Comment by dune73** [comment]
Check is failing now.

**Comment by fgsch** [comment]
Ok, I will fix that and some indentation I noticed since the last merge.

**Comment by dune73** [comment]
Thanks in advance. I'll merge immediately afterwards.

**Comment by fgsch** [comment]
Updated. 

btw, I just realised the reordering did not handle pass/nopass and phase and id are missing in some rules.

**Comment by dune73** [comment]
Thank you for fixing this.

Not been covered generally or on a few exceptions? Maybe open a separate issue.

**Pull request merged**
