### PR TITLE
Add support for shell evasions listed in #664

### PR DESCRIPTION
**Pull request by csanders-git**
Adds some of the evasions listed by @lifeforms in #664 . Generally the approach taken was to look for evasions in terms of directories, sensitive information (hostname), and possible evasions ($IFS)

### CODE REVIEW

**Comment by csanders-git** [comment]
@lifeforms suggested a test for this as well

**Comment by emphazer** [comment]
@csanders-git

what do you think about adding the following?

`````

bin/mknod
usr/bin/awk
usr/bin/base64
usr/bin/cat
usr/bin/find
usr/bin/gawk
usr/bin/hexdump
usr/bin/ln
usr/bin/mkfifo
usr/bin/ncat
usr/bin/php-cgi
usr/bin/printf
usr/bin/psed
usr/bin/sed
usr/bin/socat
usr/bin/tee
usr/bin/telnet
usr/bin/xxd
usr/bin/yes
usr/local/bin/ncat
`````

**Comment by emphazer** [comment]
it's from #961

**Comment by csanders-git** [comment]
@emphazer - check out the update :-D

**Comment by lifeforms** [comment]
Thanks people! Made a small fix and merged it 💋

**Pull request merged**
