### PR TITLE
Adding stricter sibling for 912100, cleanup

### PR DESCRIPTION
**Pull request by dune73**
I've looked at the anti-automation / dos protection rules in detail to come up with a stricter sibling.

Details of this pull request:
 - Re-formatted all rules for 3.0
 - Added a detailed description of the mechanics
 - Added a summary for every variable in use
 - Added a base check for the setting of the
   necessary parameters. Skip everything if unset.
 - Fix a bug with ip.dos_block_counter
   (used to count every blocked request twice)
 - Added a stricter sibling for paranoia level 2
   which triggers a block on the first detected
   burst of requests per IP (The standard rule 
   triggers only on the 2nd occurrence of a 
   burst).

I do not really know why the original rule waits for the 2nd burst to happen before a blocking is issued.
Whatever the intention was, it allows for a stricter sibling in PL 2 without changing the default behaviour.

If you want to this, then it may be useful to use the following
rule to monitor the behaviour:

```
SecRule REQUEST_URI "@beginsWith /index.html" "id:912001,phase:1,pass,log,msg:'\
I:DB %{ip.dos_block} \
I:DBLC %{ip.dos_block_counter} \
I:DBF %{ip.dos_block_flag} \
I:DBUC %{ip.dos_burst_counter} \
I:DC %{ip.dos_counter} \
T:DBLC %{tx.dos_block_counter} | \
T:DBT %{tx.dos_block_timeout} \
T:DCT %{tx.dos_counter_threshold} \
T:DBTS %{tx.dos_burst_time_slice} \
T:SR %{tx.static_resources}'
```

### CODE REVIEW

**Comment by dune73** [comment]
Solves issue #321.

**Comment by csanders-git** [comment]
Alright i'll run this through the tests... for my part I just finished a script that tries to automatically pretty up rules according to some standards I came up with i'll be shooting you guys an email soon and adding it to the documentation. Maybe even a blog post =-O .... Thanks for the pull :)

**Comment by dune73** [comment]
Such a pretty print script would be very helpful. 

Can we talk about it in a separate issue?

**Comment by csanders-git** [comment]
@dune73 we can absolutely - I think a new issue would be nice and we can set it for CRS 3.1

**Comment by csanders-git** [comment]
I'm going to take a look at this today - thanks for your patience .

**Comment by dune73** [comment]
User @loudly-soft has listed a few concerns with this in the issue #321. I am addressing them here.

The false positive occurring with an agent doing repeating request within a timeframe below our limit and thus running into a DoS burst can be addresses by raising the limit tx.dos_burst_time_slice. This is one of the parameters defined outside the rule-file and can thus be adopted safely. 

A different approach to handle this would simple be to do an ignore rule / whitelist the said client / IP address. Which seems to be a good approach with DoS countermeasures in general.

Also, if I am understanding correctly, this happens only with 912101 in PL2. With PL2, we assume the admin knows what he is doing and that he accepts more false positives. Hence the standard rule 912100, which is fairly tolerant until the 2nd burst. And then this strict sibling who switches into blocking defense much faster.

@loudly-soft: Does this address your concerns?

If this feels risky, it might pay to move 912101 to PL3.

**Comment by loudly-soft** [comment]
Hello @dune73.  Thank you for the quick response.  According to [this](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_981049), the proposed change for rule 912100 modifies rule condition from ```IP:DOS_BURST_COUNTER "@ge 2"``` to ```IP:DOS_BURST_COUNTER "@ge 1”```.

My understanding is that when dos_burst_counter is 1, it doesn’t imply there was a burst.  It can be the result of normal traffic.  Therefore, the proposed change will cause false positives.  To the best of my knowledge, the rules work together like this:

```
Rule 912030:
	For each request
		ip.dos_counter++

Rule 912040:
	If ip.dos_counter > DOS_COUNTER_THRESHOLD
		ip.dos_burst_counter++
		reset ip.dos_burst_counter in DOS_BURST_TIME_SLICE seconds
		ip.dos_counter = 0
 
Rule 912100 (proposed):
	If ip.dos_burst_counter >= 1
		block IP for DOS_BLOCK_TIMEOUT seconds
```

For example, if a user submits 1 request every minute, after 60 minutes, dos_counter is 60.  Assuming DOS_COUNTER_THRESHOLD is 60 (and DOS_BURST_TIME_SLICE is 30 seconds), on his next request, rule 912040 is triggered and so dos_burst_counter becomes 1.  Because dos_burst_counter is now 1, rule 912100 is also triggered and the user is blocked erroneously even though he did not submit more than 60 requests in 30 seconds.

**Comment by dune73** [comment]
@loudly-soft : The discussion on the OWASP wiki about this update are outdated. The only relevant thing now is the pull request here.

912100 is defined as:
```
SecRule IP:DOS_BURST_COUNTER "@ge 2" \
        "phase:5,\
        id:'912100',\
...
```

Then in Paranoia Level 2, there is a new / additional rule
```
SecRule IP:DOS_BURST_COUNTER "@ge 1" \
        "phase:5,\
        id:'912101',\
```

So the standard installation will not get the problem you describe. Unless I am not reading your comments correctly.

**Comment by loudly-soft** [comment]
@dune72  Ah, I see.  Now I understand your earlier comment about "this happens only with 912101 in PL2, we assume the admin knows what he is doing and that he accepts more false positives...".   Sorry for the mix up.  I'm cool with the stricter PL2 version giving more false positives.

**Comment by dune73** [comment]
Thank you for your confirmation. Glad this is sorted out. This group of rules is really hard to grasp. I tried to document it throughly, but every criticism could be valid.

**Comment by loudly-soft** [comment]
No problem.  Mostly likely, when I upgrade to the newer version in the future, I'll be generally working at < PL2 for all rules so no criticism from me. :)

I totally agree.  The rules gave me a headache to debug so I think your extra comments are going to help the next person a lot!

**Comment by lifeforms** [comment]
I love that you are cleaning up these rules and commenting the principles. These rules were always a bit mysterious and this should help people get comfortable to try them out!

My comments are as follows:

----

### Breakage introduced by skip rule phase

The PR breaks DoS protection for me with the default configuration.

On v3.0.0-rc1 branch, in paranoia level 1, requests start getting blocked at counter 203 which is as expected (two bursts).

However when I use paranoia-pull-912100 branch, the only thing I see in the audit log is request no. 202 hitting the burst limit:

`Message: Warning. Operator GE matched 2 at IP:dos_burst_counter. [file "/usr/local/etc/apache24/security2/activated_rules/REQUEST-12-DOS-PROTECTION.conf"] [line "210"] [id "912100"] [msg "Potential Denial of Service (DoS) Attack from 192.168.0.2 - # of Request Bursts: 2"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-dos"]`

but there is no blocking going on anymore.

It was quite a challenge to debug. The cause seems that 'skipping rule' 912021 executes in `phase:1`, but rule 900015 executes in `phase:request` and its variables are not yet set at point of execution of rule 912021. I can work around the problem by changing rule 900015 to:

```
SecAction \
 "id:'900015',\
  phase:1,\
```

Then blocking is working again.

Are our setups different? I include the setup conf before the CRS rule files in my Apache configuration. The default `-DREQUEST_EARLY` is set.

I used the following script to create requests:

```sh
#!/bin/sh

base_url='http://sim/?count='

i=0
while true; do
	i=$(($i + 1))
	url=${base_url}${i}
	res=`curl -s -o /dev/null -w '%{http_code}' $url`
	echo $i: $res
done
```

----

### setup.conf comment

The setup.conf should lower the bar for trying this feature, I think we should keep a short description of what the user can expect from this feature and as a minimum explain the variables, though we can do better than the previous version. What about this:

```
# -- [[ Anti-Automation / DoS Protection ]] ----------------------------------------------
#
# Optional DoS protection against clients making requests too quickly.
#
# When a client making more than 100 requests (excluding static files) within 60 seconds,
# this is considered a 'burst'. After two bursts, the client is blocked for 600 seconds.
# Requests to static files are unlimited; they are listed in 'tx.static_resources' setting.
#
# To enable the DoS protection rules, uncomment the following rule.
# For a detailed description, see rule file REQUEST-12-DOS-PROTECTION.conf.
#
#SecAction \
 "id:'900015',\
```

----

### tx.static_resources location and comment

At this moment, `tx.static_resources` in setup.conf is only used for the DoS rule, but it's set somewhere else in the file. This is not too ergonomic and it's a bit of YAGNI to create a global variable in a  remote place. To not cause too much work, we could leave it as is, but it would be nice to improve that rule's comment in that case, it currently lies a bit.

----

### tx.static_resources contents

I suggest to add `svg` and `webp` to `tx.static_resources` in setup.conf.

**Comment by dune73** [comment]
Thank you for this detailed testing Walter. I used apache bench for testing, but your script is very useful as well. I was able to reproduce the error you reported.

The error you encountered is a good catch. It did not occur in my setup, as I am not working with the
modsecurity_crs_10_setup.conf but with my own template. Fixing this as to your suggestion works just fine.

Other proposals:
- setup.conf comment: adopted. thank you
- tx.static_resources location and comment: updated comment, but left the location as is. It comes together with other variables and the limited use of this variable in the DOS protection does not mean it could not be useful elsewhere. To compensate for the remote definition, I also added a comment to the DOS parameter definition.
- tx.static_resources contents: done. thanks

I'm currently seeing issues with updating this pull request. I'll do that as soon as I figure out how. ;(

**Comment by dune73** [comment]
This pull request is being replaced by the new attempt in #359. (I was unable to push to this PR and started a new one). This one is now retired.

**Pull request closed without merging**
