### PR TITLE
Initial Support for Tuning 

### PR DESCRIPTION
**Pull request by csanders-git**
@lifeforms and @dune73 - I think this is close to what we discussed. Thoughts?

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for this PR, @csanders. I took a close view and here is my comment. Not all is necessarily useful, but I simply all the things that spring to mind when looking over the PR.

* Lot's of trailing spaces on lines
* The PR speaks of FP tuning, while we settled on the terminology Exclusion Rules. This would thus be application-specific Exclusion Rules.
* The doc does not discuss the relationship with the local rule exclusions in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example. So we have rule exclusions on one side and tunings on the other side. Without describing the common underlying concept.
* The name END-TUNING of the SecMarker does not really fit. It sounds too general.
* In https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/527#issuecomment-241277103:901990 I suggested to reserve the ID range from 9M to 10M-1 for these app-specific exclusion rules. Hence the stupid name of the rule files, which only makes sense in this light. The first drupal exclusion rule id would thus be 9001100 or so.
* I think `SecRule &TX:crs_tuning_drupal "@eq 0"`is not ideal. Set crs_tuning_drupal=0 and the exclusion rules are executed.

Sorry, if that is a lot of impolite nitpicking. I think it is important to get this right from the start.

**Comment by csanders-git** [comment]
You're fine :) this is the feedback i wanted. PR coming soon.

**Comment by csanders-git** [comment]
Ok @dune73 fixed almost everything on your list I think -- not sure about the last part, you think I should do an actual comparison?

**Comment by dune73** [comment]
Thank you for the update @csanders-git. We're getting there.

* You are only skipping in phase 2. If this is done intentionally, because we will only do rule exclusions based on information available in phase 1, then I'm OK with it. If it was a negligence, then we might want to add phase 2 from the start.
* You still check for var `tx.crs_tuning_(drupal|wordpress)`  despite calling it differently in the setup.
* Coming back to my final point, your check will fail to match if `TX:crs_tuning_wordpress` is set to 0. You will thus execute the rule exclusions if TX:crs_tuning_wordpress` is set to 0.
@lifeforms is suggesting `SecRule &TX:crs_tuning_wordpress|TX:crs_tuning_wordpress "@eq 0"` 

Finally, let me propose a few rewordings to crs-setup:

* [[ Application Specific Exclusions ]]  -> [[ Application Specific Rule Exclusions ]] 
* In such cases CRS -> In such cases the CRS 
* restrictions of the Core Rule Set -> restrictions of the CRS
* Not all applications -> Only a (very) limited set of applications

You may want to shift the "It is recommended if you run" passage below the 900130 rule.

**Comment by dune73** [comment]
@csanders-git We are depending on this being merged for other PRs. Could you look into my latest feedback please?

**Comment by csanders-git** [comment]
pushing right now

**Comment by csanders-git** [comment]
@dune73 Sorry about that, missed the comment -- I agree with almost everything -- didn't think the comment about recommended usage needed to be moved it made reading it weird. 

Beyond that thanks for the catch on the name change, i updated that to be more in line with previous expectations, missed the others. Great fix suggestions also. Regarding phase I initially did think about only using phase 1 but as phase 2 is the default i think this will be more likely to correctly function, good point to bring up.
Beyond that I think all your suggestions have been `implemented`, let me know what you think.

**Comment by dune73** [comment]
Thank you @csanders-git. This looks good to me now. Will test again, though.

@lifeforms: Any final comments from your side before we merge?

**Comment by lifeforms** [comment]
I have one very minor late insight, if we EVER would want to run some rules BEFORE the exclusions (like the potential future #591) then we might better use `903` here instead of `902` as a number prefix.

If you agree I could try to edit this PR, have never done that :)

**Comment by csanders-git** [comment]
@lifeforms no problem from my perspective if you want to try that, otherwise i can do it. let me know.

**Comment by lifeforms** [comment]
Updated the PR! If you want to know how: https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Pushing_to_someone_else.27s_pull_request

I changed the filenames, but I also made a little improvement to the crs-setup.conf.example. Now if a user wants to enable it, they have an example that they can easily uncomment without changing anything.

Also tested the settings by adding some testing rules to the exclusion files.

I'm ready to merge, what about you @dune73 ? I can spend some time on WordPress FPs tomorrow, so it would be awesome to merge this.

**Comment by dune73** [comment]
This looks good to me. Thank you for the polish. Let's merge.

**Pull request merged**
