### PR TITLE
Content-Type is case insensitive

### PR DESCRIPTION
**Pull request by fgsch**
A few fixes around how we handle the Content-Type header.

### CODE REVIEW

**Comment by dune73** [comment]
Are you sure about removing the later part of the regex at 920240?

**Comment by fgsch** [comment]
Yes, the charset doesn't really matter and no other rules looking at the Content-Type header check it.

**Comment by dune73** [comment]
@emphazer: you worked on this lately. OK with you?

**Comment by emphazer** [comment]
@dune73 yes, its okay with me ;-)

**Comment by dune73** [comment]
Very well. Thanks.

@fgs: You move from beginsWith to case insensitive regex. Why did not you introduce a t:lowercase. I think that's faster than setting up a regular expression. Or am I wrong?

**Comment by emphazer** [comment]
@dune73 good idea

**Comment by fgsch** [comment]
In the worse case scenario is considerably slower, but I can change it to use lowercase if you prefer.
The @\streq was not correct though.

**Comment by dune73** [comment]
True about the \@streq. :) 

I think I need to compile my ModSec to allow for speed tests. There is a compile time option to automatically execute every rule x thousand times. That usually gives it away.

I'd prefer lowercase. Otherwise ready to merge.

**Comment by fgsch** [comment]
@\beginWIth+lowercase will never win over @\rx ignoring the case (?i) if:

- the string is longish
- it does not match earlier

I'd be interested to know what numbers you get. I will try to take a look if/when I find time.

**Comment by dune73** [comment]
I ran a long series of tests to find about a pattern. 10M rule executions and 2 runs of each tests set (-> 20M executions).

* It takes millions of calls to really see a difference. 
* \@rx is faster than \@beginsWith for simple regexes and short strings 
* For longer strings, \@beginsWith is likely faster but it depends if there is a match and where
* The `t:lowercase` transformation thrashes every speed gain by a large margin

In conclusions: You were right. Merging.

**Pull request merged**
