### PR TITLE
Adding 21 additional tests for 942260

### PR DESCRIPTION
**Pull request by dune73**
Given we are working on fix for ReDoS on 942260, these tests may be useful.

### CODE REVIEW

**Comment by csanders-git** [comment]
All tests seem to be functioning in my testing.

**Comment by dune73** [comment]
Ready to be merged?

**Comment by csanders-git** [comment]
sorry, yes -- ready to merge

**Comment by fgsch** [comment]
There seems to be some duplication. e.g. -3, -4 and -5 are very similar. -11, -12 and -14 as well.

**Comment by dune73** [comment]
Yes they are. Yet, subtly different with whitespace. I thought it worthwhile to keep them, but if you think it's too much redundancy, then tell me and I am going to remove them.

**Comment by csanders-git** [comment]
Took me a while to realize that -- my general feeling is that there can always be more tests.

**Comment by fgsch** [comment]
I guess it depends on what they match.
If e.g. the match is on `)...` and the character before does not matter, they are duplicated.

Your call really.

**Comment by dune73** [comment]
I'm merging as is. But the technique I used allows me to create more tests for other rules. I'll be more selective there.

**Pull request merged**
