### PR TITLE
Drop 921100 for now

### LINKED ISSUE #974: 921100 incorrectly forbids "," (commas) in Transfer-Encoding
If I'm reading this rule correctly, it will trigger for both multiple Transfer-Encoding headers and a single header with multiple values separated by comma.
The latter is perfectly valid, e.g. https://tools.ietf.org/html/rfc7230#page-29 and https://tools.ietf.org/html/rfc7230#page-82.

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #974

### CODE REVIEW

**Comment by csanders-git** [comment]
Were we going to add another version of the transfer encoding rule... if i am following the convo correctly.?

**Comment by fgsch** [comment]
@csanders-git based on what you said, my understanding was the new rule is post 3.1, but regardless this rule is incorrect and we should drop it.

**Comment by csanders-git** [comment]
i'll review  the RFC to be clear.

**Comment by fgsch** [comment]
@csanders-git sure. 
If it makes things easier here are the links: https://tools.ietf.org/html/rfc7230#page-29 and https://tools.ietf.org/html/rfc7230#page-82.

**Comment by csanders-git** [comment]
@fgsch can you resolve the conflicts on this ASAP so we can include it in 3.1?

**Comment by fgsch** [comment]
@csanders-git done!

**Comment by csanders-git** [comment]
thanks!

**Pull request merged**
