### PR TITLE
Uses MULTIPART_MISSING_SEMICOLON instead of MULTIPART_SEMICOLON_MISSING

### PR DESCRIPTION
**Pull request by zimmerle**
MULTIPART_SEMICOLON_MISSING does not exists in SecLang nor in ModSec. The correct is MULTIPART_MISSING_SEMICOLON

### CODE REVIEW

**Comment by dune73** [comment]
I'm confirming this.

Ready to be merged.

**Comment by zimmerle** [comment]
tnks :+1:

**Comment by emphazer** [comment]
merged. thanks :-)

**Comment by defanator** [comment]
@dune73 @csanders-git hi guys - any estimates on when the next CRS release will be published, with this fix included? Thank you.

**Comment by dune73** [comment]
We are getting there but I won't give you a specific date.

We have defined that CRS 3.1.0 will include #990 and that one is slowly nearing completion.

If you think you would prefer to have this PR here backported to a future 3.0.3 release, then please open an issue and we'll think about it.

**Comment by victorhora** [comment]
https://github.com/SpiderLabs/ModSecurity/pull/1701 might help until the fix is out @defanator

**Comment by dune73** [comment]
Coming back to the release question: CRS 3.1 is supposed to be out in May 2018 according to this months community meeting.

**Pull request merged**
