### PR TITLE
Removing the ability for granular thresholds to block

### PR DESCRIPTION
**Pull request by csanders-git**
It was a good idea but practically it doesn't really make clear sense as part of the default rules. That being said these are still scored and can easily be made to block again in custom configurations. This is based off of ticket #407

### CODE REVIEW

**Comment by dune73** [comment]
I like that. So much simpler.

What do you think about renumbering 949190 to 949110?

**Comment by csanders-git** [comment]
@dune73 good call on the switching IDs this will keep it clean

**Comment by dune73** [comment]
@csanders-git The renaming of CRS2 `tx.inbound_anomaly_score_level` to CRS3 `tx.inbound_anomaly_score_threshold` has been done on purpose, I guess.

**Comment by dune73** [comment]
And finally noticed after merge: Is there a reason 980130 is coming without sqli score?

**Pull request merged**
