### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by fgsch**
As per the rest of the rules.

### CODE REVIEW

**Comment by fgsch** [comment]
btw, the failure from travis is related to this PR.
See https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1014

**Comment by fzipi** [comment]
Looks good to me.

**Comment by fzipi** [comment]
Sorry, reviewing the whole file, maybe you could "format your SecMarker between double quotes, using UPPERCASE and separating words using hyphens" (per CONTRIBUTING).

**Comment by fgsch** [comment]
Sure, I will add that.

**Comment by fgsch** [comment]
Updated.

**Comment by fzipi** [comment]
Nice and clean :+1:

**Review by fzipi — APPROVED** [review]
Good changeset.

**Comment by dune73** [comment]
Thank you for fixing. And sorry for merging the previous PR. I was not aware it would break things (any my cleanup still pending).

So we are ready to merge?

**Comment by fgsch** [comment]
Yes, this should be good to go.

**Comment by dune73** [comment]
Merging this despite travis failures based on joint decision it was good to go.

**Pull request merged**
