### PR TITLE
Classic SQL injection probing rule split 942370

### PR DESCRIPTION
**Pull request by emphazer**
according to https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/884

Rule 942370 has led to many false positives on a recent implementation of a CMS. Here is an extract of the POST request body that matched;

````
a:4:s:10:"@extension";s:4:"Form";s:11:"@controller";s:8:"Frontend";s:7:"@action";s:4:"show";s:7:"@vendor";s:9:"TYPO3\CMS";}2c0bd52d2261306ac8851dddef4bceafefab451a
````
This kind of payload is not out of the ordinary for certain CMS.
The only part that actually matched is ```` ";}2c0 ```` . It was only matched by a small portion of the regular expression, which is completely seperated from the rest of the regexp by an OR-operator.

This separation means that said part of the expression acts like a completely separate rule. That rule seems to be very sensitive. It only requires a quotation mark followed by a special character, then two random numbers that may be separated, for example ````"#22```` would match. This seems to be too strict to include in PL2. Because of its sensitivity seems to be a perfect addition to rule 942460 , which is in PL3 and matches any four special characters in sequence.

Therefore, I would suggest splitting the rule in two and moving this sensitive part to PL3.

### CODE REVIEW

**Comment by franbuehler** [comment]
Thanks for the PR, @emphazer!
I tested it with your extract of the POST body and it works as advertised: 
The false positive on PL2 is gone. And as expected, the new rule 942371 matches on PL3.
Perfect! In my opinion, the PR is ready to be merged.

**Comment by emphazer** [comment]
any objections?

@franbuehler 
thanks a lot for reviewing :-)

**Comment by dune73** [comment]
Thank you for the updated pr @emphazer and the review @franbuehler. We are close to merge, so it's time to put on the pedantic pants.

The rule ID makes it look like a strict sibling, but I think it is not; namely because you put it in the numbering scheme of the classical probings (-> 3/3). So a better rule ID would be 942450.

**Comment by emphazer** [comment]
@dune73 
indeed 942450 is the better choice.
done.

**Comment by dune73** [comment]
Very good. Thank you.

Now the three rules 
- 942330 PL2
- 942370 PL2
- 942450 PL3
form a group. Yet they do not have a good comment introducing them and nothing outside of the msg points to that relationship.

Could you write a comment for 942330 that introduces the topic (probings ...) and points to the other rule IDs in this group, including PL, and then for the other two rules a reference back to 942330?

If that text is correct, I will merge. Promise. ;)

**Comment by dune73** [comment]
I read you have a hard time coming up with a description @emphazer. Sorry about bothering you with this. Here is my proposal:

942330:
```
#
# -=[ SQL Injection Probings ]=-
#
# This is a group of three similar rules aiming to detect SQL injection probings.
#
# 942330 PL 2
# 942370 PL 2
# 942490 PL 3
...
```

942370:
```
# This rule is a sibling of 942330. See that rule for a description and overview.
...
```
942490:
```
# This rule is a stricter sibling of 942330. See that rule for a description and overview.
```

Apparently, my proposal to use rule ID 942450 lead to a collision. Do not know what I was thinking. Sorry. 942490 is free though. Please check and shift the rule and the regex files. The rule cleanup / logdata changes also lead to a new conflict. But I take it that is quickly resolvable.

**Comment by dune73** [comment]
Thanks @emphazer!

**Comment by emphazer** [comment]
@dune73 
i opened a new PR :-)
#985

**Pull request closed without merging**
