### PR TITLE
V3.1/dev marker

### PR DESCRIPTION
**Pull request by fzipi**
This is more cleaning up:

- fixing one typo
- changed underscore to dash in all SecMarker and skipAfter (from the contributing guidelines)

Part of #808.

### CODE REVIEW

**Comment by fgsch** [comment]
Looks good to me based on the comments on #808 though I'd prefer if we don't quote the skipAfter label. IIUC this is to make the parsing more consistent?

**Comment by fzipi** [comment]
Well, quoting the skipAfter label was per our own "string quoting" definition. After all, it's a tag. I *don't* like it either. but it was sound. Do we prefer quoting it or not?

**Comment by fgsch** [comment]
It makes sense but I'm undecided. Anyone else wants to chime in?

As a side note, based on this we should quote the ctl actions as well.

**Comment by fzipi** [comment]
Ouch!... Now I'm more convinced on rolling back those strings...

**Comment by fzipi** [comment]
@fgsch I rolled back the quoting on skipAfter, we can pospone that decision for now. Let's approve this and move on to your next set of changes 🙂

**Comment by fgsch** [comment]
LGTM. 👍

**Pull request merged**
