### PR TITLE
Update INSTALL

### PR DESCRIPTION
**Pull request by ghost**
Added a note to clarify that libinjection is bundled with ModSecurity since version 2.8.

### CODE REVIEW

**Comment by dune73** [comment]
That is a welcome addition to the INSTALL file. Thank you @cjdp.

We are seeing more and more of these useful little pull requests from the community. These mean a lot to the core team and it shows that you guys care. Please keep them coming.

PR is ready to merge from my point of view.

**Comment by lifeforms** [comment]
Absolutely cool!

I think we should merge this against `v3.0/dev` right? Correct me if I'm wrong. I've been out of the loop. ;)

**Comment by dune73** [comment]
Bullocks. Overlooked this. 

@cjdp : can you rebase against `v3.0/dev`?

**Comment by ghost** [comment]
@dune73 @lifeforms Sure thing!

I followed the instructions here: [https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/)

Looks like that did it.

**Comment by csanders-git** [comment]
Looks good from my perspective, good catch @lifeforms

**Comment by dune73** [comment]
I was ready to merge this, but now the gitter commit by @csanders-git is also part of this change set. I guess there is no harm in merging nevertheless, or will this create a mess?

**Comment by csanders-git** [comment]
Should not create any harm with merging that -- actually an oversight on my behalf.

**Comment by dune73** [comment]
Thanks for the clarification.

**Pull request merged**
