### PR TITLE
Fix DoS documentation

### PR DESCRIPTION
**Pull request by p0pr0ck5**
It's static_extensions, not static_resources

### CODE REVIEW

**Comment by dune73** [comment]
Well spotted. Thank you.

You PR targets the v3.0/master branch though, and we are developing against v3.0/dev. Can you rebase the PR?

**Comment by p0pr0ck5** [comment]
braaap, sorry. Fixed :)

**Comment by csanders-git** [comment]
Looks good to me, good idea - merging.

**Comment by dune73** [comment]
Thank you.

Just for my curiosity. What is the git command you used to rebase the PR? 

Travis CI build is still pending...

**Comment by p0pr0ck5** [comment]
@dune73 i changed the merge target, then rebased my local branch against `v3.0/dev` (i had checked out `static_extensions_doc` from `v3.0/master`). This wasn't wasn't strictly necessary, I think, but, good practices and whatnot ;)

**Comment by dune73** [comment]
Thanks.

**Pull request merged**
