### PR TITLE
Remove unnecessary END_XSS_CHECKS marker

### PR DESCRIPTION
**Pull request by dune73**
Solves issue #818.

### CODE REVIEW

**Comment by umarfarook882** [comment]
@dune73 thanks for the PR :) Sorry I was occupied with other things. So I forgot to PR #[818](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/818)

**Comment by dune73** [comment]
I had a bit of time to kill, so I thought I'd do it quickly.

**Comment by fgsch** [comment]
LGTM.

**Comment by dune73** [comment]
Time to get this merged as well.

I think it is so cosmetic, it is not worth backporting to 3.0.

**Pull request merged**
