### PR TITLE
Updated 920450 and added 'proxy'

### PR DESCRIPTION
**Pull request by csanders-git**
As described in #424 and #426

### CODE REVIEW

**Comment by csanders-git** [comment]
All fixed

**Comment by csanders-git** [comment]
regressions are super helpful. 7 are available for this rule now. all passing

**Comment by lifeforms** [comment]
Having a look now!

**Comment by lifeforms** [comment]
Hey, `Proxy-Connection` and `Via` are back! We had just removed those last month: they are not malicious, they are in actual use, and gave lots of useless log entries in CRS2. See #365 for discussion.

If you could remove those, I'll give the PR a quick spin again.

**Comment by csanders-git** [comment]
yes just noticed that literally 4 seconds ago in another test
Good look.

**Comment by csanders-git** [comment]
@lifeforms fixed. I'm going through the regressions. I haven't converted yours yet but I converted all the old CRS ones to FTW. Yours are next :)

**Comment by lifeforms** [comment]
@csanders-git Nice!

This rule is almost perfect. It blocks the headers correctly, with just one problem: `%{tx.0}` seems to be unset in the message: `[msg "HTTP header is restricted by policy "]`

It would be cool if the header name could be captured here, or otherwise, just leave it out and do `msg:'HTTP header is restricted by policy'`.

**Comment by dune73** [comment]
Was this my bad?

**Comment by csanders-git** [comment]
@dune73 - nope, all my fault. It's been a long day. Also i'd like to share a story that only you guys would appreciate. we have around 200 regression tests now (still working on converting yours @lifeforms ) but i'm running through and getting some WEIRD results. it seems like when i run things independently they trigger fine but when i run the whole suite it'll error on some random ones. After investigation, even though i'm on DetectionOnly, i find that it is (as it should) following markers if they trigger. Of course I was triggering the IP blocking. Of course the old regression tests never seemed to run into this issue, either because @dune73's DOS stuff is better or because they were soooo slow. So I haven't quite come up with the solution yet (if its add a regression check like they have in the currently rules, which i don't like or something else) ... any how - great job guys -- it's so good it's blocking our own automated scanners :-P

**Comment by dune73** [comment]
Same here. :)

My lab template removes all the DDoS/Burst/Persistend-Blocking rules (and then, when I tweak them occasionally, I forget they are not active anymore and try to track down the bug until I find the removal...

**Comment by csanders-git** [comment]
YAY they made it!

**Pull request merged**
