### PR TITLE
Add basic SQLi and XSS detection for User-Agent, Referer header

### PR DESCRIPTION
**Pull request by lifeforms**
As discussed in #402, check `REQUEST_HEADERS:User-Agent` and `REQUEST_HEADERS:Referer` against SQLi and XSS in the libinjection rules.

Since I couldn't get libinjection to fire on some XSS in User-Agents, I took the liberty of adding the header checks to the most basic regexp-based XSS rules as well.

A visual check of these regexps leads me to believe that they won't cause much FP, especially not in UAs, and unlikely in referrers.

I've also tested with a dataset of 586 user-agents which I scraped from a site. You can find that list here if you want to test: https://lf.ms/agents.txt No FPs on those user-agents found, so I think it's safe.

### CODE REVIEW

**Comment by dune73** [comment]
Looks good at first inspection. Thanks. Will check more throughly.

**Comment by csanders-git** [comment]
Went through and made unit tests for many. Seems to be working as expected.

**Comment by csanders-git** [comment]
I am also adding a util in regressions to run against those usernames

**Comment by dune73** [comment]
Thank you for the extensive UA test. This is important and gives me confidence.

This PR is really important as devops and cloud means a shift to browser-based log monitoring. XSS / CSRF via loginjection is thus a growing threat affecting the net.

I am seeing a wee bit more FPs at PL1 with the PR. Namely on 941120 XSS Filter - Category 2: Event Handler Vector on the Referer Header. That header is a beast of course and beyond our control. It may well cause a more substantial amount of FPs in individual setups (with certain partner sites).

With the attack traffic the impact is huge. As my test attack payload is based on scanners running on UA and Referer injections, this is what I was expecting.

Thank you for this pull. Glad you thought of it. Merging now.

**Pull request merged**
