### PR TITLE
XenForo: add exclusions, remove unnecessary chains

### PR DESCRIPTION
**Pull request by lifeforms**
The rules between 9006900 and END-XENFORO-ADMIN marker only hit when the filename ends in /admin.php. Therefore the chains within this section can be safely removed.

Also adds some exclusions found when enabling CRS on a large site.

### CODE REVIEW

**Comment by dune73** [comment]
We have a workaround for the Travis failures. Could you rebase your PR, so we can run Travis again, please @lifeforms?

**Comment by dune73** [comment]
Hey @lifeforms, this PR only needs to be rebased to allow us to merge.

**Comment by lifeforms** [comment]
Whoops. Updated the PR.

**Comment by dune73** [comment]
Thank you for the fix - and the rebase. Merging now.

**Pull request merged**
