### PR TITLE
Fix for issue #789

### PR DESCRIPTION
**Pull request by skidoosh**
Just a quick patch for #789 that I ran into on Friday.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you @skidoosh. That looks very good.

Unfortunately, you based against v3.0/master, but we are developing against v3.0/dev. Can you rebase your PR or submit it anew, please?

**Comment by skidoosh** [comment]
No problem. I'll get that done this afternoon and get it back over to you.

**Comment by skidoosh** [comment]
Sorry. I didn't realise I could just switch the base in the GitHub UI!

**Comment by vikas027** [comment]
Hey @dune73 , can you please merge this PR :) Thanks.

**Comment by csanders-git** [comment]
Thank you for the fix @skidoosh!

**Comment by skidoosh** [comment]
No worries. Glad I could get involved!

**Comment by dune73** [comment]
Sorry for the delay @skidoosh. Overlooked your update. Pinging me is the way to go @vikas027.

**Pull request merged**
