### PR TITLE
Update OWASP CRS Docker image to support the new upstream and 2.9.3

### PR DESCRIPTION
**Pull request by csanders-git**
The upstream now expects rules to be in /etc/modsecurity,d/
This is true across all images (nginx/apache/etc).

This also bumps us to 2.9.3 -- which as you can see below introduces two issues.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for this. I'm on vacation in Wyoming but this is inspiring me to get back to work too. Give me a 4 days to get back and then 4 days to put something up :)

**Comment by csanders-git** [comment]
This is what i am running to test

```
docker build --build-arg REPO=csanders-git/owasp-modsecurity-crs --build-arg BRANCH=Fix_Apache_Docker --build-arg COMMIT=b95b4552a5d9abdcf2063467bcdc303bac94766e -f Dockerfile-2.9-apache -t 2.9-apache .
```

**Comment by csanders-git** [comment]
i'm able to replicate failures in a local env.

**Comment by csanders-git** [comment]
apparently all of these tests are getting caught up on 

MULTIPART_STRICT_ERROR


turning this to pass causes things to pass -- lets take a gander at what we're currently doing.

**Comment by csanders-git** [comment]
So it looks like the difference MAY be the use of 2.9.3 instead of 2.9.2 :)

**Comment by csanders-git** [comment]
@victorhora ... this change is labeled as "less strict" but it appears to be more strict

https://github.com/SpiderLabs/ModSecurity/commit/7af8363fd46fd5a0bb21cc6b623d6b344f27be2a#diff-ba57ae36fd797124f3b5a6c566c1d4d2

**Comment by csanders-git** [comment]
After some investigation with @airween, it seems that this may due to discrepancies in RFC1341 and RFC2046. In 2.9.3 they switched to the more strict RFC2046 definition of allowed chars. This no longer includes ';', which is why we are seeing the false positives.

After temporarily adding 'pass' to the MULTIPART_STRICT_ERROR rule (200003), we have two pending failures -- 920130-2 and 920130-1

**Comment by csanders-git** [comment]
It appears the that 920130 is somewhat of a restatement of 200002. After changes in 2.9.3, this now works -- https://github.com/SpiderLabs/ModSecurity/commits/2c400951a59ca770c370f2f02c85e9c808c0491d/apache2/msc_reqbody.c (not sure what changes exactly). These tests now trigger the following

```
[Thu May 23 21:53:11.597654 2019] [:error] [pid 713:tid 139805581063936] [client 172.17.0.1:44032] [client 172.17.0.1] ModSecurity: Multipart parsing error: Multipart: Part missing Content-Disposition header. [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tAAAAM0"], referer: http
[Thu May 23 21:53:11.600237 2019] [:error] [pid 713:tid 139805581063936] [client 172.17.0.1:44032] [client 172.17.0.1] ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity.d/modsecurity.conf"] [line "60"] [id "200002"] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Part missing Content-Disposition header."] [severity "CRITICAL"] [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tAAAAM0"], referer: http
body.xml:7: parser error : Opening and ending tag mismatch: error line 0 and err
  </SOAP-ENV:Body><error></err>
                               ^
-----
[Thu May 23 21:53:11.946623 2019] [:error] [pid 713:tid 139805564278528] [client 172.17.0.1:44034] [client 172.17.0.1] ModSecurity: XML parser error: XML: Failed parsing document. [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tQAAAM8"], referer: http
[Thu May 23 21:53:11.947136 2019] [:error] [pid 713:tid 139805564278528] [client 172.17.0.1:44034] [client 172.17.0.1] ModSecurity: XML parser error: XML: Failed parsing document. [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tQAAAM8"], referer: http
[Thu May 23 21:53:11.947980 2019] [:error] [pid 713:tid 139805564278528] [client 172.17.0.1:44034] [client 172.17.0.1] ModSecurity: Warning. Pattern match "^5\\\\d{2}$" at RESPONSE_STATUS. [file "/etc/modsecurity.d/owasp-crs/rules/RESPONSE-950-DATA-LEAKAGES.conf"] [line "116"] [id "950100"] [msg "The Application Returned a 500-Level Status Code"] [data "Matched Data: 500 found within RESPONSE_STATUS: 500"] [severity "ERROR"] [ver "OWASP_CRS/3.1.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "WASCTC/WASC-13"] [tag "OWASP_TOP_10/A6"] [tag "PCI/6.5.6"] [tag "paranoia-level/2"] [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tQAAAM8"], referer: http
[Thu May 23 21:53:11.951516 2019] [:error] [pid 713:tid 139805564278528] [client 172.17.0.1:44034] [client 172.17.0.1] ModSecurity: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/modsecurity.d/owasp-crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "75"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [tag "anomaly-evaluation"] [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tQAAAM8"], referer: http
[Thu May 23 21:53:11.952440 2019] [:error] [pid 713:tid 139805564278528] [client 172.17.0.1:44034] [client 172.17.0.1] ModSecurity: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/modsecurity.d/owasp-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "96"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 4): individual paranoia level scores: 0, 4, 0, 0"] [tag "event-correlation"] [hostname "localhost"] [uri "/"] [unique_id "XOcWRx@ntFleSkD80EL-tQAAAM8"], referer: http
```

On the first one 200002 triggers
On the second one, we see XML Paser Errorss, not quite sure why this isn't triggering a REQBODY_ERROR - @zimmerle, any idea?

**Comment by csanders-git** [comment]
@dune73 for 920130 -- does this exist for a reason here as well as in the reccomended.conf? If not, I think we just remove it, and its tests.

for MULTIPART_STRICT_ERROR issues, I think it makes the most sense to remove those tests if this change is going to be permanent. 

Note -- i'm testing now if the MULTIPART_STRICT_ERROR has something to do with how FTW constructs the request.

**Comment by csanders-git** [comment]
It looks like those tests use \n to separate multipart data instead of \r\n

When in doubt, use the auto formatting, i.e
```
              data:
                - "-----------------------------thisissparta"
                - "Content-Disposition: form-data; name=\"payload\""
                - "Content-Type: application/xml"
                - ""
                - "<?xml version=\"1.0\"?><xml><element attribute_name=\"attribute_value\">ProcessBuilder.evil.whileclosure</element></xml>"
                - "-----------------------------thisissparta--"
``` 

instead of the inline format (which will fail in this case):
```
data: "-----------------------------thisissparta\nContent-Disposition: form-data; name=\"payload\"\nContent-Type: application/xml\n\n<?xml version=\"1.0\"?><xml><element attribute_name=\"attribute_value\">ProcessBuilder.evil.whileclosure</element></xml>\n-----------------------------thisissparta--"
```

If you want to use inline, you must use \r\n as this is what is required in HTTP :)

Special note to @spartantri  <3
and Special thanks to @zimmerle  for the help.

**Comment by csanders-git** [comment]
The following tests are now the only ones failing
920130-2
920130-1
920120-2

120-2 was strutured with a bunch of weird chars in it -- not sure how it was working before but the new MULTIPART Checking stopped it

- 'Content-Disposition: form-data; name=x'';filename="'';name=contact.txt;"'

since we were testing `['\"=]` part the regex i just went with equals instead

- 'Content-Disposition: form-data; name="fi=le"; filename="test"'

**Comment by csanders-git** [comment]
this is GOOD 2 GO pending validation by @dune73 or @lifeforms to remove the two 'redundant' rules and tests, note the tests for 290140 were already disabled.

**Comment by dune73** [comment]
Just for the clarity:

This PR removes 920130 becomes it is a replication of ModSec recommended rule 200002 and it removes 920140 because it is a replication of 200003. Since we recommend people enable the ModSec recommended rules it makes sense to remove these rules from our project.

I have not tested this PR, but I confirm it is OK to go ahead with the removal.

And great PR btw.

**Pull request merged**
