### PR TITLE
PHP variables sibling for 933130

### PR DESCRIPTION
**Pull request by csanders-git**
This is an update as described in #357. Tests are available in CRS-Regressions https://github.com/SpiderLabs/OWASP-CRS-regressions/blob/master/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933130.yaml
and are passing.

### CODE REVIEW

**Comment by lifeforms** [comment]
This is looking good!

Could you put a text file with the originals in `util/regexp-assemble/regexp-933131.data`? It would be good to track all the original sources for all regexps, so the next person maintaining the rule can easily add/remove terms and re-assemble.

I also noticed you added `t:urlDecodeUni`, do you think this should be added to the original sibling too - or perhaps to some other rules I added? As I said to @dune73 yesterday, I'm not really sure on the exact guidelines about this transform - if you think it could solve evasion problems in my new rules then I would prefer to add it there too.

**Comment by csanders-git** [comment]
Go catch on the lowercase. I will also add the comment and the data :),

**Comment by csanders-git** [comment]
@lifeforms, pushing the changes now - I realized that ./regexp-assemble.pl isn't actually in utils. Perhaps we should put it There

**Comment by csanders-git** [comment]
Also t:urldecode is already present on the original sibling :)

**Comment by csanders-git** [comment]
@lifeforms transformations in general can be a bit nasty however there are a number of things I keep in mind. 
1) transformations only apply within ModSecurity so no need to worry about modifying data and introducing a vulnerability where there wasn't one -- at worst you have introduced a FP.
2) Order matters. Base64Decode then URLDecode is different then URLDecode then Base64Decode. One must consider the order that the request will be parsed... This gets nasty for really well obfuscated text, fortunately most web servers handle things in the same way..
3) some things are handled for you depending on where you access them - so urldecode is done for ARGS, ARGS_NAMES,ARGS_POST...etc - However as a rule of thumb since these are gotten from the webserver it seems best to assumed that they won't be automatically decoded. Also areas that are not typically decoded will not have such features -- locations like REQUEST_COOKIES for instance.
4) Some transformations can ruin rules by creating bypasses. You are used to this by using things like t:lowercase on upper data. 
5) Transformations are not recursive - often this isn't an issue because of 1) but things like t:removecomments etc can in fact lead to FP or even bypasses if the attacker is real clever

There are more but these are just the ones that came to mind. To answer your question more specifically - the use of t:urldecodeuni is mostly limited to places where a typical webserver wouldn't automatically decode currently, however it isn't guaranteed. libmodsecurity should solve this issue by guaranteeing that for all versions of modsecurity the same logic is applied  

Although looking at the code it doesn't appear that right now it urldecodes ARGS collection @zimmerle

**Comment by lifeforms** [comment]
Thanks for the comments - I have much more questions about them but I guess I'll read the book first ;)

Hey. This is weird btw.

I notice your regexp is:

`(?:AUTH_TYPE)|(?:HTTP_ACCEPT)|(?:HTTP_ACCEPT_CHARSET)|(?:HTTP_ACCEPT_ENCODING)|(?:HTTP_ACCEPT_LANGUAGE)|(?:HTTP_CONNECTION)|(?:HTTP_HOST)|(?:HTTP_KEEP_ALIVE)|(?:HTTP_REFERER)|(?:HTTP_USER_AGENT)|(?:HTTP_X_FORWARDED_FOR)|(?:ORIG_PATH_INFO)|(?:PATH_INFO)|(?:PATH_TRANSLATED)|(?:QUERY_STRING)|(?:REQUEST_URI)`

But it should be compressed down to:

`(?:HTTP_(?:ACCEPT(?:_(?:ENCODING|LANGUAGE|CHARSET))?|(?:X_FORWARDED_FO|REFERE)R|(?:USER_AGEN|HOS)T|CONNECTION|KEEP_ALIVE)|PATH_(?:TRANSLATED|INFO)|ORIG_PATH_INFO|QUERY_STRING|REQUEST_URI|AUTH_TYPE)`

How did you make it? Did you run the regexp-assemble.pl that's in `util/regexp-assemble`? Do you have the newest perl module? (`cpan -D Regexp::Assemble`, I have 0.37 apparently)

**Comment by csanders-git** [comment]
its not weird... you missed a deleted message where i realized i didn't have the perl script -- but realized it was added in a later revision. I'll change it to reflect the output.

**Comment by csanders-git** [comment]
@lifeforms This should be fixed... also how cool is assemble -- right?

**Comment by lifeforms** [comment]
@csanders-git Yeah, it's cool! Too bad we don't have a reverse so I guess I'll have to Python it soon :)

**Pull request merged**
