### PR TITLE
Fix link for 941310

### PR DESCRIPTION
**Pull request by NullIsNot0**
Old link does not work anymore. Change it to new one.

### CODE REVIEW

**Comment by airween** [comment]
Hi @NullIsNot0,

first, thank you for the contribution.

Just one note: I think that would be better to use the `www` form of URL's in comments. I checked them now, we're using this case with all occurrences.

**Comment by NullIsNot0** [comment]
Thank you @airween. Fixed the link.

**Comment by airween** [comment]
Thank you.

LGTM.

**Comment by franbuehler** [comment]
In the monthly chat meeting from May 5 we decided to merge this PR:
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1749#issuecomment-623634756

**Pull request merged**
