### PR TITLE
Fix wrong regex, assembly result, in 942370

### PR DESCRIPTION
**Pull request by franbuehler**
Fix the wrong regex in 942370 (see issue #1504).
The result of the regex assemble was wrong.

### CODE REVIEW

**Comment by fgsch** [comment]
Looks good. 

Did you regenerate it to confirm it matches with the output of regexp-assemble?

**Comment by franbuehler** [comment]
Yes, it's the regenerated result of regexp-assemble.

Let's check again:

```
$ util/regexp-assemble/regexp-assemble.pl util/regexp-assemble/regexp-942370.data 
(?:[\"'`](?:\s*?(?:(?:\*.+(?:(?:an|i)d|between|like|x?or|div)\W*?[\"'`]|(?:between|like|x?or|and|div)\s[^\d]+[\w-]+.*?)\d|[^\w\s?]+\s*?[^\w\s]+\s*?[\"'`]|[^\w\s]+\s*?[\W\d].*?(?:--|#))|.*?\*\s*?\d)|[()\*<>%+-][\w-]+[^\w\s]+[\"'`][^,]|\^[\"'`])
```

Is it?
It is...

**Review by fgsch — APPROVED** [review]
Thanks! 👍

**Comment by franbuehler** [comment]
Thank you!

**Comment by dune73** [comment]
OK, let's merge this then.

Thanks for noticing the problem  @fgs and the fast response @franbuehler.

Fixes #1504.

**Comment by allanrbo** [comment]
Must have must have had a copy-paste error! Looks like I copied in an early incorrect attempt. The text in the PR description was correct, but the file was not... Sorry about that folks.

**Pull request merged**
